### ISSUE TITLE
Dependency issue with http4s (0.22 vs 0.23)

### ISSUE THREAD

**Issue by danebert** [pureconfig/pureconfig#1489]
After updating to 0.17.3 (from 0.17.2) I am seeing this dependcy conflict (we are using http4s version 0.23.11):

com.github.pureconfig:pureconfig-http4s_2.12:0.17.3 (depends on 0.22.15)

I think the 0.17.2 version of pureconfig-http4s depended on a 0.23.X version of http4s.

Snippet from sbt dependencyTree output:

[info]   +-com.github.pureconfig:pureconfig-http4s_2.12:0.17.2 [S]
[info]   | |   
[info]   | +-org.http4s:http4s-core_2.12:0.23.16

**Comment by cosminci** [comment]
[Maven Central POM for pureconfig-http4s_2.12](https://repo1.maven.org/maven2/com/github/pureconfig/pureconfig-http4s_2.12/0.17.3/pureconfig-http4s_2.12-0.17.3.pom): `http4s-core` has version `0.22.15`.

This issue is only present for Scala 2.12. Scala 2.13 pureconfig modules have the correct http4s dependency version (0.23.18).

**Comment by ruippeixotog** [comment]
Hey guys, sorry about that. The issue that led to that was fixed in #1492 and I have just released v0.17.4 ([pureconfig-http4s](https://repo1.maven.org/maven2/com/github/pureconfig/pureconfig-http4s_2.12/0.17.4/pureconfig-http4s_2.12-0.17.4.pom), [pureconfig-http4s022](https://repo1.maven.org/maven2/com/github/pureconfig/pureconfig-http4s022_2.12/0.17.4/pureconfig-http4s022_2.12-0.17.4.pom)).

**Comment by satorg** [comment]
oops, that was all my fault, sorry about that. I completely missed the project name out.
