### ISSUE TITLE
Ensuring invertible mapping in ConfigConvert[]

### ISSUE THREAD

**Issue by TeraWilliam** [pureconfig/pureconfig#15]
There are cases such as #13 where configuration values do not does not map back and there's no compile-time error.

In order to test the mappability of fields in tests it is possible to do the following:

``` scala
private def testMappability[T](from: T, namespace: String)(implicit convert: ConfigConvert[T]): Unit = {
    val rawPure: RawConfig = convert.to(from, namespace)
    val typesafeConfig: Config = {
      // there's no nice way to convert to a Typesafe .conf using the .render() method as the rawPure is a Map
      val propsConfig = rawPure.map { case (k, v) => s"$k=$v" }.mkString("\n")
      ConfigFactory.parseString(propsConfig, ConfigParseOptions.defaults().setSyntax(ConfigSyntax.PROPERTIES))
    }
    val returnedRawPure: RawConfig = pureconfig.conf.typesafeConfigToConfig(typesafeConfig)
    returnedRawPure shouldEqual rawPure
  }
```

However I would think there should be a compile-time error where possible.
Best example for this actually is `play-json` with its macro based derivations.

**Comment by melrief** [comment]
Closing this because we are going to split `ConfigConvert` into `ConfigReader` and `ConfigWriter` with #92 and we are going to have tests to check if values are converted properly to and for a configuration with a subset of the changes made for #151. Next release of PureConfig will guarantee that `ConfigConvert` instances will behave properly modulo bugs by using a comprehensive testing suite.
