### ISSUE TITLE
unable to compile nested case class with many fields in scala3

### ISSUE THREAD

**Issue by migiside** [pureconfig/pureconfig#1676]
Hi!

reproduction code:
https://scastie.scala-lang.org/YhAN9fAWT16iIfnEpg4nqQ

similar issue https://github.com/etorreborre/specs2/issues/1207

**Comment by grzegorz-bielski** [comment]
There are few possible solutions to this:
- First of all, you can change change the `-Xmax-inlines` compiler options from the default `32` to something like `50`:
```scala
scalacOptions ++= Seq("-Xmax-inlines", "50")
```
- Secondly, instead of having one `derives ConfigReader` on the top level class, you can define derive `ConfigReader`s for some of the sub fields like `ManyFieldSub` individually. This will help reducing the amount of inlines in a single derivation call.
```scala
case class ManyFields(..., f25: ManyFieldSub) derives ConfigReader
case class ManyFieldSub(f26: Int) derives ConfigReader
```
- Lastly, we can introduce in PureConfig a similar technique to the one in [specs2](https://github.com/etorreborre/specs2/blob/main/matcher/shared/src/main/scala/org/specs2/matcher/describe/Diffable.scala#L81) where inlines for products are done in batches. Perhaps a multi value variant of `summonConfigReader` would be useful here. 🤔

**Comment by migiside** [comment]
I have tried the first and second methods and both have solved this problem.

Thank you!!!
