### ISSUE TITLE
DurationConvert encodes Duration.Undefined as Duration.Inf

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#184]
Not sure why this is happening but this test fails

```scala
it should "fromS(fromD(Duration.Undefined)) == Duration.Undefined" in {
  fromS(fromD(Duration.Undefined)) shouldEqual Right(Duration.Undefined)
}
```

the error is

```scala
[info] - should fromS(fromD(Duration.Undefined)) == Duration.Undefined *** FAILED ***
[info]   Right(Duration.Inf) did not equal Right(Duration.Undefined) (DurationConvertTest.scala:86)
```

**Comment by leifwickland** [comment]
@melrief 
I understand this one a bit better now, but I'm not entirely sure what is a reasonable thing to do in this case.

`Undefined` is an instance of `Duration.Infinity` which is designed not to be equal to anything including is. It's supposed to be roughly the equivalent of `Double.NaN`. See https://github.com/scala/scala/blob/2.12.x/src/library/scala/concurrent/duration/Duration.scala#L172

The first weird bit is that we're naively converting `Undefined` to `Infinity` because, well, inheritance.

But more than that do we want to support undefined `Duration`? It doesn't seem like a particularly "pure" value.

The options I see are:
- Fail if we encounter `Duration.Undefined` because it's something of a nonsense value.
- Just make it work by making `"Duration.Undefined"` a magical string in our config dialect.

I'd love feedback on which way you guys think we ought to go.

**Comment by jcazevedo** [comment]
I'm inclined to prefer supporting `Duration.Undefined` through a new string in our config dialect, the same way we already support `"Inf"` and `"MinusInf"`. 

Even though it is unlikely that someone will directly encode the value of `Duration.Undefined` in a config file, I think we should strive to support successful round-trips in our converters.

**Comment by melrief** [comment]
I agree with @jcazevedo

**Comment by leifwickland** [comment]
@melrief @jcazevedo Thanks for the feedback.
