### ISSUE TITLE
loadConfigFromFiles with namespace argument

### ISSUE THREAD

**Issue by pjan** [pureconfig/pureconfig#257]
We're running into a case where we need to parse multiple files (so we can cleanly override substitutions across files), but at the same time want to tell pureconfig from wich namespace to parse.

Looking at the api, it seems this case is not covered. If confirmed, and I get a pointer on how you would like the signature to look like (since the original function accepts varargs, the namespace can't be at the back as in other functions that take it), I'm happy to put up a PR for this.

**Comment by melrief** [comment]
We probably need another [`loadConfigFromFiles`](https://github.com/pureconfig/pureconfig/blob/master/core/src/main/scala/pureconfig/package.scala#L274) with the namespace as second argument, something like

```scala
 def loadConfigFromFiles[Config: ConfigReader](files: Traversable[Path], namespace: String): Either[ConfigReaderFailures, Config]
```

I'd like the opinion of another author about this because in theory the functionality can already be implemented with the current API by the user by just loading the configurations separately using the typesafe config library and then by feeding the result to `loadConfig`.

**Comment by leifwickland** [comment]
@pjan Do you want to load into a single namespace or different namespaces per file?

**Comment by ruippeixotog** [comment]
This is already covered with the new `ConfigSource` API. Closing.
