### ISSUE TITLE
Unexpected behavior with Option

### ISSUE THREAD

**Issue by kellen** [pureconfig/pureconfig#263]
I'm seeing some inconsistent and unexpected behavior with `Option`.

When a field is optional in a config class, it defaults to `None`, so this works:

```
import com.typesafe.config.ConfigFactory
import pureconfig._

val emptyConfig = ConfigFactory.parseString("")

case class A(a: Option[Int])
assert(A(None) == loadConfigOrThrow[A](emptyConfig))
```

If, however, you move the `Option` into the parameters for `loadConfigOrThrow`, no such defaulting occurs, and the load fails with an exception:

```
case class B(a: Int)
assert(None == loadConfigOrThrow[Option[B]](emptyConfig, "b")) 
// fails with exception
```

Also, defaults are not respected:

```
case class C(a: Option[Int] = Some(10))
assert(C(Some(10)) == loadConfigOrThrow[C](emptyConfig))
// fails, a == None
```

For case `B`, it appears a top-level check would work, something like: 
```
def handleOption[T: ConfigReader : ClassTag](
  config: Config, 
  path: String
): Either[ConfigReaderFailures, T] = {
  val reader = implicitly[ConfigReader[T]]
  val isOption = classOf[Option[_]] == implicitly[ClassTag[T]].runtimeClass
  reader.from(
    if(isOption && !config.hasPath(path)) null else config.getValue(path)
  )
}
```

**Comment by ruippeixotog** [comment]
Hi @kellen! Thanks for submitting this. They are both interesting corner cases - I guess we didn't give much thought to them before.

First of all, note that pureconfig does not treat `Option[T]` as a special type - there are no explicit checks if a type is an option to allow missing keys. There is an `AllowMissingKeys` trait that any `ConfigConvert` instance can extend in order to get full control of what to return in such a case.

That said, case `B` is pushing the boundaries of what a namespace can and should do. When `loadConfigOrThrow` is called with a namespace, pureconfig looks first for the sub-config to read, and only after that is the appropriate `ConfigConvert` used. When a namespace is specified, it is implied to be mandatory; the type that a user requests does not change that. While I'm tending to prefer the current behavior, I agree that this need to be well documented.

On the other hand, the case with `C` seems more clearly a bug. The default values of the case class should have precedence over the "presence" status of the key, in my opinion.

**Comment by kellen** [comment]
@ruippeixotog In the case of [iheartradio/ficus](https://github.com/iheartradio/ficus), which has similar goals (and from which I am switching) `B` is handled like this:

```
import net.ceedubs.ficus.Ficus._
import net.ceedubs.ficus.readers.ArbitraryTypeReader._
import com.typesafe.config.ConfigFactory

val emptyConfig = ConfigFactory.parseString("")
case class B(a: Int)
assert(emptyConfig.as[Option[B]]("b").isEmpty) // ok
```

Which seems more intuitive to me. 

In the case of `C`, ficus requires more wrangling since it requires a config path for extraction. My solution for this has been to place a "local" config at a known path, then extract from there: 

```
case class C(a: Option[Int] = Some(10))
assert(C(Some(10)) == emptyConfig.atPath("foo").as[C]("foo")) // ok
```

**Comment by ruippeixotog** [comment]
I opened #264 for changing the behavior of `C` to the one you showed.

Regarding `B`, the solution typically shown in the pureconfig documentation is writing a case class for the outer level. I guess we can make pureconfig fail with `KeyNotFound` only if the `ConfigConvert` is not `AllowMissingKey`; otherwise, we pass `null` to the reader and return its result. @melrief, @leifwickland, @jcazevedo, @derekmorr, what do you think about this?

I still think it would be a bit error-prone to do that; with that behavior, you stop distinguishing the case where you specify the correct namespace but the config "intentionally" doesn't exist and the case where you mistype the namespace. However, not supporting @kellen's case cleanly seems somewhat limiting.

**Comment by jcazevedo** [comment]
I guess it's reasonable to assume that if we have the following:

```scala
case class B(a: Int)
case class A(b: Option[B])
```

This would hold:

```scala
loadConfig[A](emptyConfig).right.map(_.b) == loadConfig[Option[B]](emptyConfig, "b")
```

I tend to prefer what you suggested (failing with `KeyNotFound` only if the `ConfigConvert` is not `AllowMissingKey`).

**Comment by ruippeixotog** [comment]
Right now, that doesn't hold for any type that is not represented by an object:

```
scala> loadConfig[Int](ConfigFactory.parseString("a = 1"), "a")
com.typesafe.config.ConfigException$WrongType: String: 1: a has type NUMBER rather than OBJECT
  at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:159)
  at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
  at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
  at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
  at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:264)
  at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:270)
  at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:37)
  at pureconfig.package$.getConfigSafe(package.scala:34)
  at pureconfig.package$.loadConfig(package.scala:97)
  ... 39 elided
```

In fact, it throws an exception when it clearly should at least return a `Left`.

Using `loadConfig` with `namespace` requires the value in that namespace to be a proper `Config` - the same requirement used for root configs. I guess that the initial purpose of that method was to make a config file hold various sub-configs that different components could read as their relative root configs.

If we made `loadConfig` with a namespace support loading from any config key, then I would also be supportive of treating `AllowMissingKeys` the same way as it is treated inside a case class. We'd also be able to simplify many examples of custom readers in the documentation.

One more question: what about this case?

```scala
case class B(a: Int)
case class A(b: Option[B])

loadConfig[Option[B]](emptyConfig, "c.d")
```

If the namespace was `"c"`, we agree that we should return `None` with the new behavior. Should we do the same with nested non-existing keys?

**Comment by jcazevedo** [comment]
> If the namespace was "c", we agree that we should return None with the new behavior. Should we do the same with nested non-existing keys?

Probably. 

However, if the intent of using any of the `loadConfig*` variants with `namespace` was to scope sub-configs as you described, then it makes sense to only allow it if the namespace points to a `ConfigValue` that could be lifted to a `Config` (in this case, only `ConfigObject`). In that case, I'm inclined to prefer always failing if the namespace doesn't exist, but I'm not too strong about it.

**Comment by melrief** [comment]
I interpret `loadConfig[Option[B]]` as "try to load `B` and if you fail give me back a `Right(None)`" which doesn't make much sense imho. You can convert the result of a `loadConfig` into an `Option` by just calling `toOption` on it or by working on single errors, like `KeyNotFound`. Said that, @ruippeixotog your solution of failing with `KeyNotFound` only if the `ConfigConvert` is not `AllowMissingKey` can probably make the behavior of PureConfig more consistent. While I don't understand the use case, I think making consistent PureConfig is important and I'm ok with changing the behavior as you said.

For nested non-existing keys, I would always fail.

One last thing: `loadConfig` should never throw exception and the fact that it does is imho a bug.

**Comment by ruippeixotog** [comment]
I could understand the use case you really want to load a single field from a config - although admittedly it doesn't seem a very common one. But I like the idea that you can load any value with a `ConfigReader` from a config, a thing that you can't easily do now.

I think that we all agree on this algorithm for `loadConfig[A]` at a given `namespace`:

- Get the config value of the last parent in `namespace` (e.g. if we pass `a.b.c`, we navigate to `a.b`), failing with `KeyNotFound` or `WrongType` if adequate;
- Retrieve the value at the "leaf" of the namespace (possibly `null`);
- If the value is `null` and the `ConfigReader` for `A` is _not_ an `AllowMissingKey`, fail with `KeyNotFound`; otherwise, return the result of the reader.

**Comment by melrief** [comment]
@ruippeixotog I agree, thanks.

**Comment by leifwickland** [comment]
@ruippeixotog Seems reasonable.

**Comment by kellen** [comment]
> I interpret loadConfig[Option[B]] as "try to load B and if you fail give me back a Right(None)" which doesn't make much sense imho.

I have a reading with a minor semantic difference: "load B if it exists, otherwise give me `Right(None)`"

An example of when you may wish to do this: Say you have some software that can be extended with plugins where the plugins are enabled by providing a list of the plugin names. Since you may have no plugins, this list is optional. In scala code, I'd model this as `Option[List[String]]`.

So in the plugin handler, I need to load the (user-defined) list of plugins from config. e.g. `loadConfigOrThrow[Option[List[String]]](config, "plugins")` I don't necessarily have a larger config model that needs to be represented, so I only want the one value.

Two alternatives are to either (a) require the user to define an empty list `plugins: []` or (b) defensively check `config.hasPath` for any optional values. Both of these seem fragile.

**Comment by ruippeixotog** [comment]
I think that `loadConfig[Option[B]]` can't be interpreted as anything other than "try to load B as an `Option[B]` and give me back a `Right(value)` if you do". I think that we should really emphasize that for pureconfig, `Option[B]` is _not_ some special type representing "existence" of a value. If I ever want to create my own `CustomOption` type, I'd be able to give it the same behavior, and if I wanted to disallow absent `Option` values (for example, by forcing users to write `null`), I could too. So `loadConfig` of an `Option` should be read as just that - loading the value in a config as an `Option`.

I understand the use case for your example and I agree that we should support it - the behavior I descried above does the job. But regarding your concrete example, I would really model the list of plugins as `List[String]`, as it already represents "0 or more plugins" - the `Option` is redundant there.

Did you know that you can use the special `reference.conf` file to put defaults for your config files? [Akka](http://doc.akka.io/docs/akka/snapshot/scala/general/configuration.html#listing-of-the-reference-configuration) and [Play](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/resources/reference.conf) do that extensively and it's my favorite place to place default config values such as `plugins: []`. The underlying Typesafe Config library loads that file automatically for you with lower precedence than `application.conf`, and so pureconfig does too.
