### ISSUE TITLE
Loading configs to a specific subclass that is defined in a java library

### ISSUE THREAD

**Issue by melodious** [pureconfig/pureconfig#265]
I have a 3rd party java library with an interface and several implementations. I would like to be able to load configurations to the correct subclass similar to what is done for sealed traits and case classes. I assume I need to do something custom but I am not sure where to begin. Any help would be appreciated.

**Comment by ruippeixotog** [comment]
Hi @melodious! In order to support any custom type you have to provide an implicit instance of `ConfigReader`, as shown in the [Support new types](https://github.com/pureconfig/pureconfig/blob/master/docs/support-new-types.md) section on the documentation.

For creating a `ConfigReader` for a Java interface, I'd probably go with either subclassing `ConfigReader` directly in order to provide your implementation or using [`ConfigReader.fromFunction`](https://github.com/pureconfig/pureconfig/blob/master/core/src/main/scala/pureconfig/ConfigReader.scala#L114). In both cases you are provided a `ConfigValue` which you can read and have to return an `Either[ConfigReaderFailures, T]`.

Let me know if this helped!

**Comment by melrief** [comment]
Hi @melodious, thanks for the question. I would like to expand the answer from @ruippeixotog because I think that supporting new **complex** types, like a set of implementation for an interface in Java, is an important topic to discuss. The README explains how to create `ConfigReader` instances for simple types but it lacks information for complex types. I'll try to explain here how to support something similar to Scala's sealed families of case classes.

There are three methods to support something like a Java interface with several implementations, each one with its own pros and cons. I will describe the three ways and then tell you what is, in my opinion, the right way.

### Data type to support

First of all, let's start with the data type that we want to support. You didn't write the example so I'll create a toy example based on what I know that you want to support. Let me know if I understood correctly. The example is one interface and two implementations:

```java
// Identifiable.java
public interface Identifiable {
    String getId();
}
```

```java
// Class1.java
public class Class1 implements Identifiable {

    private String id;

    public Class1(String id) {
        this.id = id;
    }

    public String getId() {
        return this.id;
    }
}
```

```java
// Class2.java
public class Class2 implements Identifiable {

    private String id;
    private int value;

    public Class2(String id, int value) {
        this.id = id;
        this.value = value;
    }

    public String getId() {
        return this.id;
    }

    public int getValue() {
        return this.value;
    }
}
```

### Method 1: Implement `ConfigReader[Identifiable]` manually

This is what's written in the README and what @ruippeixotog was suggesting. It consists in manually creating a `ConfigReader[Identifiable]`:

```scala
implicit val identifiableConfigReader = ConfigReader.fromFunction({
  case obj: ConfigObject =>
    Option(obj.get("type")) match {
      case None =>
        Left(ConfigReaderFailures(KeyNotFound("type", ConfigValueLocation(obj))))
      case Some(t) if t.valueType() == ConfigValueType.STRING =>
        t.unwrapped().asInstanceOf[String] match {
          case "class1" => extractId(obj).right.map(new Class1(_))
          case "class2" =>
            for {
              id <- extractId(obj).right
              value <- extractValue(obj).right
            } yield new Class2(id, value)
          case x =>
            Left(ConfigReaderFailures(CannotConvert(obj.toString,
              "Identifiable", s"type has value $t instead of class1 or class2",
              ConfigValueLocation(obj),
              "")))
        }
      case Some(t) =>
        Left(ConfigReaderFailures(CannotConvert(obj.toString,
          "Identifiable", s"type has value $t instead of class1 or class2",
          ConfigValueLocation(obj),
          "")))
    }
  case wrong =>
    Left(ConfigReaderFailures(WrongType(wrong.valueType(), Set(ConfigValueType.OBJECT), ConfigValueLocation(wrong), "")))
})

private def extractId(obj: ConfigObject): Either[ConfigReaderFailures, String] =
  Option(obj.get("id")) match {
    case None =>
      Left(ConfigReaderFailures(KeyNotFound("id", ConfigValueLocation(obj))))
    case Some(id) =>
      ConfigReader[String].from(id)
  }

private def extractValue(obj: ConfigObject): Either[ConfigReaderFailures, Int] =
  Option(obj.get("value")) match {
    case None =>
      Left(ConfigReaderFailures(KeyNotFound("value", ConfigValueLocation(obj))))
    case Some(value) =>
      ConfigReader[Int].from(value)
  }
```

**pros**: The main feature of this method is that you take control over PureConfig on how to decode your configuration. PureConfig takes your `ConfigReader[Identifiable]` as blackbox and applies it when it has to read your configuration
**cons**: The main feature of this method is also the drawback, because by taking control over PureConfig in how to read sealed families of case classes, you prevent PureConfig from doing its magic. For instance, you prevent PureConfig from using the `CorpoductHint` as strategy to read `Identifiable`. This is, generally speaking, not a good idea. In theory you want PureConfig features also for your custom class.

### Method 2: Use a Scala copy of the Java configuration

PureConfig works out-of-the-box with Scala sealed familes of case classes and one simple solution to your problem is to

1. define a hierarchy of Scala classes mimicing you Java classes
2. define a conversion from this Scala close to the Java configuration

In the case above, you could do this

```scala
// define the "dummy" scala hierarchy following what we have in Java
sealed trait IdentifiableDummy {
  def id: String
  def toIdentifiable: Identifiable = this match {
    case Class1Dummy(id) => new Class1(id)
    case Class2Dummy(id, value) => new Class2(id, value)
  }
}
final case class Class1Dummy(id: String) extends IdentifiableDummy
final case class Class2Dummy(id: String, value: Int) extends IdentifiableDummy

// change the coproduct hint to tell PureConfig that the type value specified
// is the name of the class - "Dummy" because we want the type to be the one
// we specified in Java, not in the dummy scala types
implicit val identifiableCoproductHint = new FieldCoproductHint[IdentifiableDummy]("type") {
  override protected def fieldValue(name: String): String =
    name.take(name.length - "Dummy".length).toLowerCase
}

// we tell PureConfig that to read Identifiable, it has to read IdentifiableDummy first
// and then map it to Identifiable
implicit val identifiableConfigReader: ConfigReader[Identifiable] =
  ConfigReader[IdentifiableDummy].map(_.toIdentifiable)
```

**pros**: it's idiomatic and elegant. You use a type supported by PureConfig to extract the data you need from your configuration and then you map if to your data structure. Note that this method follows what you usually do in other libraries (e.g. Circe) to support new datatypes and it's both composable and nice to read
**cons**: you need to duplicate your configuration and PureConfig needs to do two steps to read it.

### Method 3: Give a Generic representation of your configuration

PureConfig is based on Shapeless Generics which is used to represent data structures in a generic form. The reason why in method 2 PureConfig was able to decode `IdentifiableDummy` but not `Identifiable` prior our code is that `IdentifiableDummy` has a Generic instance provided by Shapeless while `Identifiable` doesn't. This method consists in adding the generic representation for the configuration.

Let's start with the concrete classes `Class1` and `Class2`. PureConfig needs to know two things in order to read them:

1. Their generic representation
2. For each field in the generic representation, if there is a default value for that field or not.

Point 1 is solved by the code:

```scala
// create the singleton idw for the field id
val idw = Witness('id) 

implicit val class1Generic = new LabelledGeneric[Class1] {
  // the generic representation of Class1 is the field id of type String
  override type Repr = FieldType[idw.T, String] :: HNil

  // mapping from/to is trivial
  override def to(t: Class1): Repr = field[idw.T](t.getId) :: HNil
  override def from(r: Repr): Class1 = new Class1(r.head)
}

// create the singleton valuew for the field value
val valuew = Witness('value)

implicit val class2Generic = new LabelledGeneric[Class2] {
  // the generic representation of Class2 is the fields id of type String and value of type Int
  override type Repr = FieldType[idw.T, String] :: FieldType[valuew.T, Int] :: HNil

  // mapping from/to is trivial here too
  override def to(t: Class2): Repr =
    field[idw.T](t.getId) :: field[valuew.T](t.getValue) :: HNil
  override def from(r: Repr): Class2 = new Class2(r.head, r.tail.head)
}
```

Point 2. is trivial because both `Class1` and `Class2` don't have default values for fields:

```scala
implicit val class1Default = new Default.AsOptions[Class1] {
  override type Out = Option[String] :: HNil
  override def apply(): Out = None :: HNil
}

implicit val class2Default = new Default.AsOptions[Class2] {
  override type Out = Option[String] :: Option[Int] :: HNil
  override def apply(): Out = None :: None :: HNil
}
```

After we added this, PureConfig is able to load `Class1` and `Class2` from configuration. The second and final part of this method is to add the generic representation of `Identifiable` as sealed family of `Class1` and `Class2`, or coproduct of them if you want:

```scala
val class1w = Witness('Class1)
val class2w = Witness('Class2)

implicit val identifiableGeneric = new LabelledGeneric[Identifiable] {
  override type Repr =
    FieldType[class1w.T, Class1] :+:
    FieldType[class2w.T, Class2] :+:
    CNil

  override def to(t: Identifiable): Repr = t match {
    case class1: Class1 => Inl(field[class1w.T](class1))
    case class2: Class2 => Inr(Inl(field[class2w.T](class2)))
  }

  override def from(r: Repr): Identifiable = r match {
    case Inl(class1) => class1
    case Inr(Inl(class2)) => class2
    case _ => ???
  }
}
```

**pro**: more efficient than method 2 because instead of using another data type, it provides the missing pieces of information to PureConfig so that PureConfig can derive the `ConfigReader[Identifiable]` by itself
**cons**: Shapeless magic. If you know Shapeless, this is doable, otherwise I would be careful.

### Summary

Ok but then what is the method to use in this case? A good way to decide is to write down when each method should be used:

- **method 1** is good to add support for simple types or types that don't need PureConfig's way to decode products (classes) or coproducts (sealed families of classes)
- **method 2** is good to add support for complex types with a similar structure of what is supported by PureConfig, e.g. products and coproducts
- **method 3** is good when method 2 is too slow or when you need to add only part of the information to let PureConfig work, e.g. if you had the generic representation of `Class1` and you just have to add the default instance for the arguments

Based on this, @melodious I would suggest you to use **method 2**. In libraries like PureConfig, the best way to add a new data type is often to take something supported by the library and "map it" to your new data type.

I hope this helps and sorry for the delay in the answer but it took a while to write down everything.

**Comment by ruippeixotog** [comment]
Great tutorial for the creation of readers for custom complex types, @melrief! We should definitely have a thing such as this in our documentation :) I also agree that method 2 is a superior solution when you want to reuse the derivation capabilities provided by pureconfig.

**Comment by melodious** [comment]
@melrief Thank you so much for this very clear tutorial. This helps a ton!

**Comment by leifwickland** [comment]
@melrief Excellent work. I second the idea that belongs in the docs.

**Comment by mariop-da** [comment]
@ruippeixotog @leifwickland I was going to do it after Rui proposed it. I didn't have much time available in the previous days but I hope I'll be able to do it soon. I also agree this mini tutorial should be in the docs 😄 .

**Comment by melrief** [comment]
@ruippeixotog @leifwickland I was going to do it after Rui proposed it. I didn't have much time available in the previous days but I hope I'll be able to do it soon. I also agree this mini tutorial should be in the docs 😄 .
