### ISSUE TITLE
Introduce cursors in ConfigReaders and possibly ConfigWriters

### ISSUE THREAD

**Issue by jcazevedo** [pureconfig/pureconfig#287]
Currently, `ConfigReader`s lack context on where in the configuration we are, since we deal with `ConfigValue`s directly. Amongst other things, this forces us to rely on calling the `improveFailures` method explicitly to add better context to reading failures. Custom implementations of `ConfigReader`s might not call it and therefore the error locations become unreliable. Introducing cursors would allow us to keep track of context in a consistent way.

Besides improving the context of errors, we can also use cursors to pass information relevant for reading `ConfigValue`s to readers down in the tree.

**Comment by ruippeixotog** [comment]
After studying the best way to refactor our handling of failures in order to make use of `ConfigCursor` to facilitate the context propagation, I am inclined to split our failures in two different models:

- a `FailureReason` indicating the reason of a failure without contextual information such as the location or path in the config where it occurred;
- the old `ConfigReaderFailure`, which besides a non convert-related failure such as `CannotReadFile`, can be a `ConvertFailure(reason: FailureReason, location: Option[ConfigValueLocation], path: String)`.

For this, I'll need both non-empty lists of `ConfigReaderFailure`s and non-empty lists of `FailureReason`s. In order not to repeat code, I think I can:

1. Start depending on `cats-core` and use its `NonEmptyList` class;
1. Create our own `NonEmptyList` class, probably a simplified version of the cats one;
1. Start using simple `List`s instead, disregarding the (IMO) residual decrease in type-safety.

Which of the approaches do you prefer?

**Comment by ruippeixotog** [comment]
Another related decision is whether we want our external API to deal with collections of failures as it is now or to expose a composite pattern instead (i.e. a result is an `Either[ConfigReaderFailure, A]` where `MultipleFailures(failures: NonEmptyList[ConfigReaderFailure])` is a possible `ConfigReaderFailure`). This has the advantage of simplifying the handling of results with single failures (the vast majority of the cases) but provides a more cumbersome approach to combining and dealing with multiple results later.

**Comment by ruippeixotog** [comment]
After some more fiddling with the code, I found out that I actually don't need to handle non-empty lists of `FailureReason` (at least not with the existing features). This problem may need a solution later but for now, I'll keep`ConfigReaderFailures` as it is then.
