### ISSUE TITLE
could not find implicit value

### ISSUE THREAD

**Issue by sidhant92** [pureconfig/pureconfig#292]
Hey guys im getting the following error:

could not find implicit value for parameter reader: pureconfig.ConfigReader

And the funny thing is this error is very random. Sometimes its coming sometime its not. What should i do to fix it.

**Comment by sidhant92** [comment]
Okay i noticed that im getting this error whenever my case class includes a variable whose type is a sealted trait having many sub case classes.

**Comment by leifwickland** [comment]
Hi, @sidhant92.

Sorry you're having trouble. 

To encode an ADT like your sealed hierarchy, PureConfig needs a little help because there's no native representation of it. Either you'll need to create an enum for it (see https://github.com/pureconfig/pureconfig/tree/master/modules/enumeratum or  https://github.com/pureconfig/pureconfig/tree/master/modules/enum) or provide a `CoproductHint` that tell PureConfig how you want to encode the members of your ADT. See the test for `EnumCoproductHint` for an example of how to do the latter. https://github.com/pureconfig/pureconfig/blob/67af0decdbef67d64e25e33c8f200a1f626faac3/core/src/test/scala/pureconfig/CoproductHintSuite.scala#L42

Please let me know if that helps.

Leif

**Comment by sidhant92** [comment]
@leifwickland I used this https://github.com/pureconfig/pureconfig/tree/master/modules/enumeratum

But here instead of case object i had case classes.
The implicit issue was solved after this.
But then i started getting this error:
Left(ConfigReaderFailures(CannotConvert.
It cant map it to the correct case class.

**Comment by sidhant92** [comment]
@leifwickland And with no changes done the config is loading absolutely fine. Its just that its not compiling it. 
And once i load the config in console after that it compiles also successfully until i do a clean compile.

**Comment by leifwickland** [comment]
@sidhant92 Apologies. I gave you bad advice. I missed the fact that you had `case class`es, not `object`s. I'm sorry.

This page documents the behavior that should be happening in your case:
https://github.com/pureconfig/pureconfig/blob/master/docs/override-behaviour-for-sealed-families.md

Theoretically, it should compile without anything additional. To successfully read the config, the config element which represents the ADT member would need a `type` member which contained a value equal to the name of the class.

If that's not the behavior you're seeing, please give us a reproducible case we can investigate.

Again, I'm sorry I led you astray originally.

Leif

**Comment by sidhant92** [comment]
@leifwickland Yes thats the use case. I am using the type parameter in the config to load the correct case class. The problem is that when the case classes hierarchy is in different files the compiler is giving the implicit error. But manually in the console it loads the config correctly.
The issue is somewhat related to this:
https://github.com/pureconfig/pureconfig/issues/98

**Comment by leifwickland** [comment]
@sidhant92,

I think the problem arises when you put the classes of the hierarchy into different files. More specifically when you put the classes into different files, the trait can no longer be `sealed`. The Shapeless magic underlying PureConfig requires that the trait be `sealed`.

You can see the effect of removing sealed in the PureConfig unit tests. If you remove `sealed` from [`AnimalConfig`](https://github.com/pureconfig/pureconfig/blob/67af0decdbef67d64e25e33c8f200a1f626faac3/core/src/test/scala/pureconfig/AnimalConfig.scala#L3) and then run `sbt test`, you'll see a mess of errors beginning with:

```
[error] /Users/lwickland/src/pureconfig/core/src/test/scala/pureconfig/CoproductConvertersSuite.scala:17: could not find implicit value for parameter cc: pureconfig.ConfigConvert[pureconfig.AnimalConfig]
[error]   checkArbitrary[AnimalConfig]
[error]                 ^
```

Hopefully, that just means that you need to make your trait `sealed`. if you can't, then you need to provide a manually constructed `CoproductHint` for your hierarchy.

Please let me know if that helps.

Thanks,

Leif

**Comment by sidhant92** [comment]
@leifwickland My traits are sealed just defined in different files.
Please look at the repo i have created to demonstrate the issue:
https://github.com/sidhant92/pureconfig-test

On compiling it gives the error:
could not find implicit value for parameter reader: pureconfig.ConfigReader[config.Zoo]

**Comment by leifwickland** [comment]
@sidhant92,

Thanks for the sample project. It sure looks to me like the `could not find implicit value for parameter reader` goes away if the files are in the same directory as each other, regardless of which package they are in. If I `mv src/main/scala/config/* src/main/scala` the code compiles.

I'm saying that's a good solution; it's simply what I saw.

@ruippeixotog @melrief @jcazevedo Is failure around Shapeless failing to build implicits when the source files are in a different directory a known problem?

Thanks,

Leif

**Comment by leifwickland** [comment]
I tried moving the classes in @sidhant92's sample out of the root package, but that didn't fix the problem. 

I tried moving the `AnimalConfig` in pureconfig's unit tests into a nested directory to mimic what @sidhant92's sample project, but that didn't replicate the problem.

**Comment by ruippeixotog** [comment]
Hi @sidhant92,

I tried running your project and I was able to replicate the problem. However, if I use the latest Scala 2.11.x version (2.11.11) the problem doesn't seem to happen.

Before looking deeper into the problem, is there any reason why you're not using Scala 2.11.11? If not, updating it would solve your problem.

**Comment by leifwickland** [comment]
Good point, @ruippeixotog. I had tried updating to 2.11.8, but that didn't fix the problem. It appears that 2.11.9 is the point that something was fixed in scalac.

**Comment by sidhant92** [comment]
@ruippeixotog No specific reason. Its just that we were using 2.11.4 on our prod systems and upgrading it might cause some issues. We can try doing that and see what happens.

**Comment by leifwickland** [comment]
It looks like Scala 2.12.0 has the same bug. It's fixed in 2.12.1. Perhaps we ought to recommend minimum scala versions in the README.

**Comment by ruippeixotog** [comment]
I'd like first to find out the problem with PureConfig on this specific code, since it shouldn't happen at all.

We don't warn about minimum Scala versions because patch versions (A.B.C) of the same minor (A.B) should be binary compatible among them. Moreover, Scala 2.11.8 and 2.12.0 were "latest versions" in the past and we never had that bug, so something like this appearing now is very strange...

**Comment by ruippeixotog** [comment]
Unfortunately, the problem seems to be #205 once more... In short, the compiler is not loading the subclasses of `Animal` before shapeless tries to derive a generic representation of `Animal`.

You can try the following in your example project to observe the strangeness of the issue:

- Replace `loadConfig[Zoo]` by `loadConfig[Cat]` and check that the code compiles (you can comment the `configsMap += ...` line temporarily for that effect);
- Replace it again with `loadConfig[Dog]` and check that the code still compiles;
- Revert it to `loadConfig[Zoo]` and check that the code now magically compiles.

https://github.com/scala/scala/pull/5284 is the PR that was merged against Scala 2.12.1 and backported later to Scala 2.11. It greatly improves the compiler on that aspect, but it does not eliminate completely the bug, as seen in PR #278. More importantly, it adds a compiler warning like `knownDirectSubclasses of ${sealedtrait} observed before subclass ${subclass} registered` when the issue occurs, which is very helpful.

@sidhant92 since this is a compiler bug, I think the only viable solution for you would be to upgrade to the latest 2.11 version. I understand the risk of updating things in production systems, but it should be very safe to upgrade from one 2.11 version to another (and even to 2.12), as binary compatibility is kept between those versions.

@leifwickland with this investigation, I'm inclined to agree that we should write a warning in the README about this. The fact that the knownDirectSuclasses error is silent before 2.11.11 and 2.12.1 is very misleading...

**Comment by sidhant92** [comment]
@ruippeixotog Thanks for the info. Yes ill update my scala version to solve the issue.
I have updated the repo https://github.com/sidhant92/pureconfig-test
Now again im getting the same error with version 2.11.11. Can you please check whats happening.
Thanks

**Comment by leifwickland** [comment]
@sidhant92 It appears that as of commit `ccf7bf1`, upgrading to 2.11.11 fixes your problem.

The issue you're seeing now is a different problem as far as I can tell that's due to the addition of:
```
animalSize: Option[Map[AnimalSize, String]]
```
It seems there are two problems there.
1. If I simplify that to just `size: AnimalSize` then I start getting errors like:
```
knownDirectSubclasses of AnimalSize observed before subclass Small registered
```

2. Even if I rearrange your code to avoid that problem, using `AnimalSize` as the key of a map seems to always fail. 

@ruippeixotog, is there a reason that an enumeratum enum would fail as the key of a map but work as the value?

**Update:** Oh, right. This is failing because PureConfig only supports maps which use strings as the key, as described [here](https://github.com/pureconfig/pureconfig#supported-types)

**Comment by sidhant92** [comment]
@leifwickland Thanks for the info. Sorry had missed had that detail.

**Comment by ruippeixotog** [comment]
I think that we can close this since #294 was merged and the other issues were already solved. Please let us know if we missed something!
