### ISSUE TITLE
Support auxiliary constructors for case classes

### ISSUE THREAD

**Issue by briangordon** [pureconfig/pureconfig#308]
I found it nice that if there's a default argument in a case class then pureconfig will use it to construct the instance. For example for the config:

```
{
  activity = rafting
  distance-miles = 100
}
```

This will work fine:

```
case class VacationOption(activity: String, distanceMiles: Int, timeTaken: Option[Int] = None)
```

But if we want to put some more sophisticated logic into the constructor:

```
case class VacationOption(activity: String, distanceMiles: Int, timeTaken: Int) {
  def this(activity: String, distanceMiles: Int) = this(activity, distanceMiles, distanceMiles / 30 + 60)
}
```

pureconfig will fail with `Key not found` with the above config.

[The other means](https://github.com/pureconfig/pureconfig/blob/master/docs/add-support-for-complex-types.md) of handling this seem prohibitively complex. If shapeless is able to deal with auxiliary constructors that would be easier.

**Comment by ruippeixotog** [comment]
Hi @briangordon! I don't think shapeless has support for auxiliary constructors out-of-the-box. Shapeless treats case classes as algebraic data types and, as such, as products of a fixed arity. In fact, even the support Scala has for them is a bit awkward, since they always have to pass through the main one...

One way of doing this without much effort, if you don't mind repeating the computation of the default, is to make use of `contramapConfig`:

```scala
val readerWithDefault = ConfigReader[VacationOption].contramapConfig {
  case co: ConfigObject =>
    if(co.containsKey("time-taken")) co
    else co.withValue("time-taken", ConfigValueFactory.fromAnyRef(co.toConfig.getInt("distance-miles") / 30 + 60))
}
```

I omitted all error handling for the cases where the root config is not an object and where `distance-miles` is not present or is not an int. https://github.com/pureconfig/pureconfig/issues/287 will simplify the manipulation of these raw configs.

**Comment by briangordon** [comment]
Thanks so much for your help. Absent support for auxiliary constructors, I think `contramapConfig` is pretty much perfect for what I needed.
