### ISSUE TITLE
Key not found error 

### ISSUE THREAD

**Issue by allquantor** [pureconfig/pureconfig#309]
Hi,

thie most trivial example I could imagine just not working.

```
 case class Worker(workerId: String)

 val c = parseString(
    """{ workerId = "1"}""")

 val worker = loadConfigOrThrow[Worker](c)
```
=>>
```
  at 'worker-id':
    - Key not found. You might have a misconfigured ProductHint, since the following similar keys were found:
       - 'workerId' 

```
Is there something I do wrong? Thanks

**Comment by jcazevedo** [comment]
By default, PureConfig expects config keys to be written in kebab case and the associated field names to be written in camel case, that's why it is failing to find the expected key `worker-id` (since `workerId` maps to `worker-id`). As the error message hints at, you can override that behaviour by putting a different implicit `ProductHint` in scope. You can read more about how to do it in [this section](https://pureconfig.github.io/docs/overriding-behavior-for-case-classes.html) of the documentation.

**Comment by allquantor** [comment]
I see. Thanks!

**Comment by rrwright** [comment]
Updated documentation link (?): https://pureconfig.github.io/docs/overriding-behavior-for-case-classes.html
