### ISSUE TITLE
Cats RC1 Release Milestone

### ISSUE THREAD

**Issue by ChristopherDavenport** [pureconfig/pureconfig#322]
As pureconfig is used, and some of us would like to test prior to cats 1.0 release. Could we get a release milestone for cats `1.0.0-RC1`? If not totally cool, but thought I'd put it out there.

**Comment by keirlawson** [comment]
Now that Cats 1.0.0 is out I'd like to take a look at doing this, however `MonadReader`, for which we provide an instance for `ConfigReader` is now `ApplicativeLocal` and has been moved out into the `cats-mtl` library. In order to avoid bringing in a dependency on said library (as apparently it may yet undergo major change before stabilising) I'd like to propose dropping this instance for the time being (but keeping the `MonadError` instance).  How do people feel about this?

**Comment by melrief** [comment]
I would prefer to drop the instance. We can add another module if we really want the `MonadReader` instance but the `cats` module should not require `cats-mtl` in my opinion.

**Comment by ruippeixotog** [comment]
I agree with both of you, we can create a `pureconfig-cats-mtl` later if anyone wants it.

How will we do regarding cross-compilation? Does it make sense to rename our current module to `pureconfig-cats-0.9` or something like that and make `pureconfig-cats` 1.0-only? Or can we just compile the same codebase for the two versions?

**Comment by keirlawson** [comment]
I don't think compiling against both versions will be possible, as I understand it the changes are substantial, including artifact incompatibility. Given the whole ecosystem seems to be moving forward onto Cats 1.0.0, I would be inclined to leave PureConfig 0.8.0 for any users stuck on Cats 0.9.0 and only support Cats 1.0.0 going forward.

**Comment by melrief** [comment]
I agree with @keirlawson, I would prefer to move to Cats 1.0.0 like most of libraries have done.

**Comment by ruippeixotog** [comment]
Ok, that surely seems easier for us. I'm not much into the cats ecosystem, so if you think it's not worth it to continue to support 0.9 I'm all for it :)

**Comment by derekmorr** [comment]
Agreed - let's drop it and add a new module for MTL.
