### ISSUE TITLE
Support the HOCON 1.3.2 Period Format for java.time.Period

### ISSUE THREAD

**Issue by ches** [pureconfig/pureconfig#359]
I hoped this would Just Work™, but it appears pureconfig's `Period` support predates that of Typesafe Config 1.3.2 (lightbend/config#478) and doesn't know about the new HOCON unit syntax yet:

```scala
case class Conf(period: java.time.Period)

val config = ConfigFactory.parseString("""{ period = 5 years }""")

config.getPeriod("period") // => java.time.Period = P5Y

pureconfig.loadConfigOrThrow[Conf](config) // BOOM
```

pureconfig does handle `ConfigFactory.parseString("""{ period: P5Y }""")`, but Typesafe `getPeriod` does not, and it's not quite as nice for humans.

It's unfortunate that Typesafe Config doesn't seem to expose its parsers, so users would need to copy-and-paste a big hunk of its package-private code to define an overriding `ConfigReader[Period]` instance supporting the syntax.

I thought I wouldn't be the last to expect this to work, thus opening this issue. If I have the chance, I'll look more closely at the existing `Duration` support and try to come up with a suitable PR. Should pureconfig try HOCON format parsing and fall back to ISO-8601 `Period.parse` transparently? This doesn't quite fit the mold of existing configurable converters.

Thank you for the library, I'm enjoying the type richness and boilerplate reduction!

**Comment by ruippeixotog** [comment]
Hi @ches, thanks for submitting the issue! I was not aware that Typesafe config supported `Period` natively.

> Should pureconfig try HOCON format parsing and fall back to ISO-8601 Period.parse transparently? This doesn't quite fit the mold of existing configurable converters.

I'm fine with this approach. `Period` [isn't a configurable converter](https://github.com/pureconfig/pureconfig/blob/master/core/src/main/scala/pureconfig/BasicReaders.scala#L92) as it doesn't depend on a time zone and we already have `Duration` ([declaration](https://github.com/pureconfig/pureconfig/blob/master/core/src/main/scala/pureconfig/BasicReaders.scala#L108), [implementation](https://github.com/pureconfig/pureconfig/blob/master/core/src/main/scala/pureconfig/DurationConvert.scala)) in the same situation. Since those two formats do not overlap, we can safely try parsing one and falling back to the other.

**Comment by ches** [comment]
Thanks for implementing this @ruippeixotog!
