### ISSUE TITLE
Pureconfig's config file does not support uppercase and underscores

### ISSUE THREAD

**Issue by talosu** [pureconfig/pureconfig#394]
Pureconfig's config file does not support uppercase and underscores.

`application.conf`
```
DW {
  conn_type =type
}
```
class 
```
case class Db(CONN_TYPE: String
             )

case class DbAll(DW: Db)

```

`error log: `
```sql
Key not found: 'dw'. You might have a misconfigured ProductHint, since the following similar keys were found:
       - 'DW'
Key not found: 'conn-_type'. You might have a misconfigured ProductHint, since the following similar keys were found:
       - 'conn_type'
```

**Comment by jcazevedo** [comment]
PureConfig uses the concept of field mappings to describe how fields of case classes should be converted to fields in the configuration file. You can read more about it in the project's documentation: https://pureconfig.github.io/docs/overriding-behavior-for-case-classes.html#field-mappings. 

The configuration of field mappings is included in a `ProductHint`, which is used by PureConfig to configure how the derived reader and writer for a particular product should behave.

In your case, you have two different field mappings: one (for `DbAll`), in which no transformation should be performed between fields in the case class and fields in the documentation; and another (for `Db`), in which fields in the case class should be converted to lower case. In order to support deriving readers for `Db` and `DbAll` that behave as you are expecting, you must have two implicit `ProductHint`s in scope:

```scala
implicit val phDbAll = ProductHint.apply[DbAll](fieldMapping = ConfigFieldMapping(identity))
implicit val phDb = ProductHint.apply[Db](fieldMapping = ConfigFieldMapping(_.toLowerCase))
```

Note that the default behavior of PureConfig is to convert `camelCase` field names in case classes to `snake-case` field names in the configuration.

**Comment by ruippeixotog** [comment]
@ererermao, did @jcazevedo's response solve your problem?

**Comment by ruippeixotog** [comment]
I'll assume @jcazevedo's answer solves the problem and close this. If the issue persists, feel free to reopen!
