### ISSUE TITLE
Disable automatic derivation by default

### ISSUE THREAD

**Issue by nigredo-tori** [pureconfig/pureconfig#396]
#304 was closed for an unrelated reason, however the issue remains.

(copied from https://github.com/pureconfig/pureconfig/issues/304#issuecomment-407960683).

Automatic derivation makes the field names etc. part of the API, which is not ideal. My team uses the explicit approach in similar cases (JSON codecs, etc.) - any encoding should be performed by an explicitly specified codec, and missing codec should cause a compilation error. Thus we need an option to disable automatic derivation entirely.

One way to achieve that (which is what `circe` project does) would be to remove `DerivedReaders`/`DerivedWriters` from `ConfigReader`/`ConfigWriter` objects, and make them accessible through an explicit import of some package object. We can even move those to a separate module, getting rid of the `shapeless` dependency in `core`. This would make this library a lot more flexible, at the cost of adding an import to the existing code.

**UPD**: to clarify, this issue is about shapeless-powered derivation for arbitrary ADTs. `Map`/`Option`/`TraversableOnce` typeclass instances should remain available by default.

**Comment by wedens** [comment]
Yeah. It'd be great to be able to choose between auto-derivation/semi-auto-derivation/no-derivation based on imports (like circe does).

**Comment by jcazevedo** [comment]
I also think that being able to choose between automatic and semi-automatic derivation is a good idea. It also makes it easier for one to compose over `ConfigReader`s/`ConfigWriter`s that PureConfig automatically derives.

**Comment by ruippeixotog** [comment]
I also like the idea of not importing derivations for case classes and sealed traits automatically. The way Circe does it seems like a nice solution.

The only thing that bothers me is how to do the transition - this is a major breaking change, one that will cause compilation errors on pretty much every user as they have to add a possibly large number of `import` statements. IMO, the ideal scenario would be to have a transitional version where:

- all old code would still work, but with a deprecation warning indicating that they will have to import something in order to keep automatic derivation in the future;
- all packages/imports for the new structure already there, so that users could do the migration without waiting for the following version.

We could leverage macros to an extent, if that helped and was not too complex to implement. Does this seem feasible?

**Comment by nigredo-tori** [comment]
@ruippeixotog, this seems tricky to get right, and it also delays the feature... If all we need to do is to suggest adding an import in the places that broke, why not add it to the "implicit not found" message? This way we can rip the band-aid right off.

**Comment by jcazevedo** [comment]
> We could leverage macros to an extent, if that helped and was not too complex to implement. Does this seem feasible?

I don't think that transitional version will be of much use for users interested in semi-automatic derivation, since importing `pureconfig._` will always enable automatic derivation.

I guess we can release a new version that still only supports automatic derivation, deprecates the automatic derivations for ADTs coming from the `pureconfig` package and point users to the new `pureconfig.auto` package. Another release can follow that introduces the `pureconfig.semiauto` package and removes automatic derivations for ADTs in the `pureconfig` package.

However, I don't mind not having a smooth transition, provided that we make it clear for users what they have to do to keep their current code working, both in the CHANGELOG and in the `implicitNotFound` messages, as @nigredo-tori suggested.

**Comment by leifwickland** [comment]
My vote would be for no transitional version so long as there are clear migration docs as other have mentioned.

**Comment by ruippeixotog** [comment]
I don't like very much the approach of using `implicitNotFound` for communicating breaking changes in particular types (case classes and sealed traits) since they will show on missing readers of every class, possibly leading to even more confusion. Moreover, people using our "better implicit not found" message won't see it, as the message is replaced for a more detailed one.

I'm ok with releasing a new version with these changes without a transitional one :) I can work on this. So, if I understood correctly, the idea is:

- To remove automatic readers and writers from the `ConfigReader` and `ConfigWriter` companion objects;
- To have a `pureconfig.semiauto` package or object containing the readers and writers for case classes and sealed traits a non-implicit form. Are you thinking in something like `val myCaseClassReader: ConfigReader[CC] = deriveReader[CC]` and `val mySealedTraitReader: ConfigReader[ST] = deriveReader[ST]`? Or do you prefer to have methods with different names for the two cases, like `productReader` and `coproductReader`?
- To have a `pureconfig.auto` package or object that provides implicits for the methods above.

Is this correct?

Also, should we move these objects to a separate `pureconfig-generic` module, as @nigredo-tori suggested? Even though I like the flexibility it provides and the decrease in the number of dependencies, I feel that it may be a burden for people who want this to "just work".

Right now I think it's very easy to get started into PureConfig - people just call `loadConfig[MyConf]` and magic happens for them. We are saying now that there's an extra import to add before, which isn't anything problematic, IMO. Adding two dependencies instead of one is a bit stranger, as few people want configs loaded without using case classes and they don't always have this level of insight of the inner workings of the library. Opinions?

**Comment by wedens** [comment]
If you're worried about multiple dependencies, you can always publish an artifact that depends on both `pureconfig-core` and `pureconfig-generic`.

IMO it's not that burdensome to add two dependencies instead of one.

> Even though I like the flexibility it provides and the decrease in the number of dependencies, I feel that it may be a burden for people who want this to "just work".

Not having shapeless as a transitive dependency can be useful in some cases (less potential for conflicts).

> Right now I think it's very easy to get started into PureConfig - people just call loadConfig[MyConf] and magic happens for them.

IMO magic should be opt-in insead of opt-out.

**Comment by jcazevedo** [comment]
> Or do you prefer to have methods with different names for the two cases, like `productReader` and `coproductReader`?

I prefer having single `deriveReader`/`deriveWriter` methods.

> Also, should we move these objects to a separate `pureconfig-generic` module, as @nigredo-tori suggested? Even though I like the flexibility it provides and the decrease in the number of dependencies, I feel that it may be a burden for people who want this to "just work".
>
> Right now I think it's very easy to get started into PureConfig - people just call `loadConfig[MyConf]` and magic happens for them. We are saying now that there's an extra import to add before, which isn't anything problematic, IMO. Adding two dependencies instead of one is a bit stranger, as few people want configs loaded without using case classes and they don't always have this level of insight of the inner workings of the library. Opinions?

I think the most common use case for PureConfig (and one that we promote throughout the documentation) uses generic derivation to read a configuration file to a case class. Taking that into account, if we were to split into two different modules, I guess most people would be adding the `pureconfig-core` and `pureconfig-generic` dependencies. At least right now, I think splitting into two different modules would complicate things for the majority of users, with little benefit besides removing the `shapeless` dependency from `pureconfig-core`.

**Comment by nigredo-tori** [comment]
> At least right now, I think splitting into two different modules would complicate things for the majority of users

One way to alleviate this is to use even more modules. ^_^
1. `pureconfig-core` for the base functionality.
2. `pureconfig-generic` for derivation.
3. `pureconfig` - an empty convenience module that depends on these two.

This way we get the desired flexibility, while the users that don't need it won't have to to change their `libraryDependencies`.

**Comment by fommil** [comment]
If I sent a PR to remove the inheritance of the `Generic` instances from the companion and require a `import pureconfig.generic._` is that something that would be accepted and released fairly soon? It is a minimal effort change on both the side of pureconfig and downstream users, requiring only an import to remain source compatible.

I did a compiler profile of my codebase and discovered that pureconfig generic derivation is the bottleneck, so this is something I'm interested in spending a few days on.

**Comment by ruippeixotog** [comment]
@fommil I'd be ok with that, but I'm convinced with the idea of separating this in different `pureconfig-core` and `pureconfig-generic` modules, as long as we keep publishing `pureconfig` as a bundle of `pureconfig-core` and `pureconfig-generic` in order to make it easy for users to get started.

If we are going to do this, I'd prefer to do all dependency structure changes in a single version change. If @jcazevedo and @leifwickland agree, I'll commit to do this until the end of next week and release a version right after that. Is that a reasonable timeline for you, @fommil?

**Comment by fommil** [comment]
Sounds great!

**Comment by fommil** [comment]
BTW, to add some numbers on this. In **just** our functional tests (15 files) of **just** one project, this bug is making us take 82s instead of 8s to compile.

I have monkey patched the `Derived*` classes to remove the `implicit` keyword, effectively disabling shapeless yet retaining binary compatibility.

I am in the process of writing a magnolia based deriver for `ConfigReader`, to be semi-auto combined with `@deriving`, that I expect to deliver a (max) 90% reduction in compiletime.

I'm going to use this as an example in my book about why full auto (and especially shapeless) should never be enabled by default on a typeclass :wink:

**Comment by jcazevedo** [comment]
> One way to alleviate this is to use even more modules. ^_^

I like that idea.

**Comment by fommil** [comment]
What I'm using to get a 90% reduction in compiletime, combined with `@deriving`... not hard to add annotations to support all the various product/coproduct hints. I don't care about those things, just the defaults.

```scala
package pureconfig

import magnolia._
import scala.language.experimental.macros
import scalaz._, Scalaz._

import pureconfig.error._

// WORKAROUND: https://github.com/pureconfig/pureconfig/issues/396
object MagnoliaConfigReader {
  type Typeclass[a] = ConfigReader[a]

  private val naming: ConfigFieldMapping =
    ConfigFieldMapping(CamelCase, KebabCase)

  def combine[A](ctx: CaseClass[ConfigReader, A]): ConfigReader[A] =
    c =>
      // WORKAROUND: https://github.com/propensive/magnolia/issues/119
      if (ctx.isValueClass) {
        ctx.parameters.toList
          .traverse(_.typeclass.from(c))
          .map(ctx.rawConstruct)
      } else
        for {
          cur <- c.asObjectCursor
          bits <- ctx.parameters.toList.traverse { p =>
            val key = naming(p.label)
            val tc = p.typeclass
            cur.atKeyOrUndefined(key) match {
              case undefined if undefined.isUndefined =>
                p.default match {
                  case Some(v) => Right(v)
                  case None =>
                    tc match {
                      case _: AllowMissingKey => tc.from(undefined)
                      case _ => cur.failed(KeyNotFound.forKeys(key, cur.keys))
                    }
                }
              case defined => tc.from(defined)
            }
          }
        } yield ctx.rawConstruct(bits)

  def dispatch[A](ctx: SealedTrait[ConfigReader, A]): ConfigReader[A] =
    c =>
      for {
        cur <- c.asObjectCursor
        name <- cur.atKey("type").flatMap(_.asString)
        hit <- {
          ctx.subtypes
            .find(_.typeName.short.toLowerCase == name.toLowerCase)
            .toRight(ConfigReaderFailures(CannotParse(name, None)))
            .flatMap { s =>
              s.typeclass.from(c)
            }
        }
      } yield hit

  def gen[A]: ConfigReader[A] = macro Magnolia.gen[A]
}
```

**Comment by fommil** [comment]
btw I don't think the traversable, option or map derivations need `Lazy`... they should go on the companion directly (or on some lower priority mixin).

**Comment by ruippeixotog** [comment]
One issue I can foresee with auto-derivation is that, by explicitly importing the generic readers, they gain priority over specialized readers that we keep in `ConfigReader`'s companion object. For example, if we keep the reader for traversables in the companion object and import the generic readers, `List` will start being read as a sealed trait instead of a traversable, am I correct?

One solution I can see is to make the generic readers object also contain (by extending the trait) the rest of the readers, but since this will "elevate" the priority of all our readers in implicit search users may start to see implicit conflicts - for example, if they have their own `Option` reader and have it imported separately. I'd really like to avoid that, as it's not at all a trivial migration for users. Any ideas?

**Comment by fommil** [comment]
@ruippeixotog 

auto derivation is the devil and nobody should be using it.

Basically you're encountering all the problems that Miles has been trying to fix in the compiler (see export-hook for the current abandoned hack), and that me and Jon Pretty have been independently solving in scalaz-deriving and magnolia. Fundamentally, if you want to use shapeless for full auto derivation today, you have to manually deal with typeclass coherence yourself if you also want custom instances. It's not something I recommend.

BTW, a week might be too long for me to wait. Would you be ok if I sent a PR to do the split on Monday or Tuesday? I'm fairly confident I know how you'd structure this as I've done it a few times before myself. I only have one week before I leave my Scala job and, well, at that point I really don't care :smile: but I'd definitely like to leave my team with 5 second test compiles instead of 2 minutes.

I suspect you'll want to use magnolia instead of shapeless, ultimately, and that means abandoning all your ProductHint and CoproductHint things and using annotations instead. I am currently writing up a fully documented example for json encoding / decoding for my book that should give you lots of ideas. https://leanpub.com/fpmortals/read#leanpub-auto-magnolia

I can add the beginnings of a magnolia module and you can add support for annotations later. You might be able to get it to work with ProductHint and CoproductHint for legacy compat, but I don't recommend it.

It's a work in progress and is using an unreleased version of Magnolia... but a release is imminent.

**Comment by leifwickland** [comment]
@ruippeixotog said:
> If we are going to do this, I'd prefer to do all dependency structure changes in a single version change. 

Yes, please.

> ... separating this in different pureconfig-core and pureconfig-generic modules, as long as we keep publishing pureconfig as a bundle of pureconfig-core and pureconfig-generic in order to make it easy for users to get started.

Yes, please.

**Comment by ruippeixotog** [comment]
@fommil I totally agree with the analysis and I also had a lot of trouble with the implicit search precedence in the Scala compiler before. If I had to redesign this library from the ground-up, I'd think thrice before I decided to add auto-derivation.

The trouble is that, for me, any change that breaks user code to a point where it becomes nearly impossible for them to migrate without heavy source changes on their side should be avoided at all costs. While adding extra imports or requiring new dependencies is certainly acceptable, making users refactor their whole projects' organizations so that their custom readers continue to work together with automatically derived ones is not. In my view, neither reducing compile times nor preventing accidental auto-derivation of readers is worth this level of compatibility break.

While I am not hopeful that we'll find a magical solution for the typeclass precedence problem, we may have an alternative way that keeps migration simple. For example, what if we remove the generic readers from the companion object of `ConfigReader` and add in our `pureconfig-generic` new entrypoint methods `loadConfigAuto*` that, instead of requiring a `ConfigReader` directly, required an instance of a new `AutoConfigReader` typeclass? We could make it so that `AutoConfigReader` could be implicitly created from a `ConfigReader` and, with lower priority, from shapeless derivations. While I didn't test this solution, it seems that it supports the three modes (no derivation, semi-auto and auto derivation) and only requires "regular" users to change their usual `loadConfig` entrypoint to `loadConfigAuto`. Can you foresee any issue with this approach?

**Comment by ruippeixotog** [comment]
I realized minutes after posting this that this approach would only work for top-level generic derivations. Forget the dumb idea above... 😞

**Comment by fommil** [comment]
The only user change needed will be adding the generic import. Which I'm personally not going to use.

**Comment by ruippeixotog** [comment]
Hmm, maybe I didn't understand this correctly then... Let's consider the following user code:

```scala
case class InnerConf(...)

object InnerConf {
  // a custom reader for `InnerConf`
  implicit val innerConfReader: ConfigReader[InnerConf] = ...
}

case class OuterConf(...)

object Main {
  import pureconfig.generic._

  val conf = loadConfig[OuterConf]
  ...
}
```

Currently, PureConfig would use `innerConfReader` for `InnerConf` and the shapeless-derived reader for `OuterConf`. With the explicit `generic` import here, wouldn't the shapeless-derived reader have precedence over `innerConfReader` for `InnerConf`?

I'm asking for this example in particular because I usually organize my implicit instances this way and I know a lot of code bases doing this.

**Comment by fommil** [comment]
You're trying to fix a problem that can't be fixed with shapeless.

**Comment by fommil** [comment]
(the closest you can get to making this work is https://github.com/milessabin/export-hook )

**Comment by ruippeixotog** [comment]
I understand that the general problem of combining custom instances of a typeclass with generic derivation cannot be solved with shapeless-like typeclass derivation and is better suited to direct macros/annotations, which have full control to do implicit searches and generate code accordingly.

I still believe that we don't need a generalized solution to this problem and, as such, we can benefit from alternative solutions that "avoid" the core issue.

Please take a look at [this POC](https://gist.github.com/ruippeixotog/8e3fac127ceef2c7d264bac13604a8c6) and let me know what you think. Basically, we can use a secondary `LowPriorityConfigReader` typeclass (defined in `core`, but with no instances there) to create `ConfigReader` instances with low priority (taking advantage of the fact that we have great control over the priority of the implicits in the companion object). The import of an `auto` package provides implicit `LowPriorityConfigReader` instances that still have less priority than user-defined `ConfigReader`s, while a `semiauto` package can have methods that create proper `ConfigReader`s.

**Comment by fommil** [comment]
I can't say I'm a fan of the `LowPriorityConfigReader`... this is not what this normally means. You're trying to introduce typeclass incoherence through indirection. You don't need macros to fix this problem, it is solved by not recursing... i.e. what people call "semiauto". Simply remove the `implicit` keyword from your entry point.

I'll send a small PR doing the first step, making the generic derivation opt-in. You guys can do what you want after that with regards to package structure. From my perspective, I just want the ability to opt-out entirely from shapeless.

**Comment by fommil** [comment]
bah, sorry. I give up. This has all been set up in a very complicated way and I don't have enough motivation to fix it.

My fix is to clone the repo locally in my project, remove the `extends DerivedReaders` from the companion, and add Option / Traversable derivations that don't need `Derivable` or `Lazy`.

Good luck with your refactor. Hopefully my team will be able to handle the upgrade in my absence!

**Comment by fommil** [comment]
BTW, for the benefit of anybody who is wondering how I fixed this in my work codebase:

1. copy the exact version of `DerivedReaders.scala` from this repo into your project
2. replace `implicit def` with `def` and `implicit final` with `final` everywhere in this file.
3. introduce the below `orphans.scala` (note that I've removed superfluous `Lazy` and `Derivation` wrappers. BTW, your `F` doesn't need to extend `Traversable`.)
4. install magnolia 0.9.1 and use the belowe `magnolia.scala`
5. install https://gitlab.com/fommil/scalaz-deriving with the below `deriving.conf` in `resources`

```scala
// orphans.scala
package pureconfig

object orphans {
  implicit def deriveOption[T: ConfigReader]: ConfigReader[Option[T]] =
    DerivedReaders.deriveOption[T]

  implicit def deriveTraversable[T: ConfigReader, F[T] <: Traversable[T]](
    implicit CBF: collection.generic.CanBuildFrom[F[T], T, F[T]]
  ): ConfigReader[F[T]] = DerivedReaders.deriveTraversable

  implicit def deriveMap[T: ConfigReader]: ConfigReader[Map[String, T]] =
    DerivedReaders.deriveMap[T]

  final implicit class ConfigReaderXMap[A](val self: ConfigReader[A]) extends AnyVal {
    def xmap[B](f: A => B, g: B => A): ConfigReader[B] = self.map(f)
  }
}
```

```scala
// magnolia.scala
package pureconfig

import magnolia._
import scala.language.experimental.macros
import scalaz._, Scalaz._

import pureconfig.error._

// WORKAROUND: https://github.com/pureconfig/pureconfig/issues/396
object MagnoliaConfigReader {
  type Typeclass[a] = ConfigReader[a]

  private val naming: ConfigFieldMapping =
    ConfigFieldMapping(CamelCase, KebabCase)

  def combine[A](ctx: CaseClass[ConfigReader, A]): ConfigReader[A] =
    c =>
      for {
        cur <- c.asObjectCursor
        bits <- ctx.parameters.toList.traverse { p =>
          val key = naming(p.label)
          val tc = p.typeclass
          cur.atKeyOrUndefined(key) match {
            case undefined if undefined.isUndefined =>
              p.default match {
                case Some(v) => Right(v)
                case None =>
                  tc match {
                    case _: AllowMissingKey => tc.from(undefined)
                    case _ => cur.failed(KeyNotFound.forKeys(key, cur.keys))
                  }
              }
            case defined => tc.from(defined)
          }
        }
      } yield ctx.rawConstruct(bits)

  def dispatch[A](ctx: SealedTrait[ConfigReader, A]): ConfigReader[A] =
    c =>
      for {
        cur <- c.asObjectCursor
        name <- cur.atKey("type").flatMap(_.asString)
        hit <- {
          ctx.subtypes
            .find(_.typeName.short.toLowerCase == name.toLowerCase)
            .toRight(ConfigReaderFailures(CannotParse(name, None)))
            .flatMap { s =>
              s.typeclass.from(c)
            }
        }
      } yield hit

  def gen[A]: ConfigReader[A] = macro Magnolia.gen[A]
}
```

```deriving.conf
pureconfig.ConfigReader=pureconfig.MagnoliaConfigReader.gen
```

**Comment by jcazevedo** [comment]
> Please take a look at [this POC](https://gist.github.com/ruippeixotog/8e3fac127ceef2c7d264bac13604a8c6) and let me know what you think. Basically, we can use a secondary LowPriorityConfigReader typeclass (defined in core, but with no instances there) to create ConfigReader instances with low priority (taking advantage of the fact that we have great control over the priority of the implicits in the companion object). The import of an auto package provides implicit LowPriorityConfigReader instances that still have less priority than user-defined ConfigReaders, while a semiauto package can have methods that create proper ConfigReaders.

I like that approach. It seems to be similar to what Circe does, using the [`Exported`](https://github.com/circe/circe/blob/master/modules/generic/shared/src/main/scala/io/circe/generic/AutoDerivation.scala) type.

I'm not against adding a module providing generic derivation of `Reader`s and `Writer`s using Magnolia, but I'd rather have the auto/semi-auto split using shapeless introduced first.

**Comment by ruippeixotog** [comment]
As @jcazevedo said (as I was writing this) `circe` seems to do more or less the same way as I suggested, but with a clearly more elegant name :)

```scala
case class Exported[T](instance: T) extends AnyVal

// included by the `Decoder` companion object
private[circe] trait LowPriorityDecoders {
  implicit def importedDecoder[A](implicit exported: Exported[Decoder[A]]): Decoder[A] = exported.instance
}

// inclued by the `auto` package
trait AutoDerivation {
  implicit def exportDecoder[A]: Exported[Decoder[A]] = macro ExportMacros.exportDecoder[DerivedDecoder, A]
  implicit def exportEncoder[A]: Exported[ObjectEncoder[A]] = macro ExportMacros.exportEncoder[DerivedObjectEncoder, A]
}
```

@fommil I understand your concerns with this - I really do. Subverting the problem by defining a new typeclass to request indirectly seems like a hack and not a proper solution for the problem. However, as I mentioned, it's important for us not to break user code in updates unless the migration is relatively straightforward for them.

Since `circe` implemented this with success, I'll proceed to implement it this week in PureConfig.

**Comment by fommil** [comment]
"Subverting the problem by defining a new typeclass to request indirectly " I didn't recommend doing so :smile: 

All I'd like is for the `implicit`s to be removed from the companion so that I can choose not to use shapeless.
