### ISSUE TITLE
The description of the UnknownKey failure hould include the actual key.

### ISSUE THREAD

**Issue by katameru** [pureconfig/pureconfig#413]
In `FailureReason.scala` we have:
```
final case class UnknownKey(key: String) extends FailureReason {
  def description = s"Unknown key."
}
```
Having the actual key in the description would be helpful in finding typos in configuration files.

**Comment by ruippeixotog** [comment]
The reason why none of the `FailureReason` descriptions (not only `UnknownKey`) contain the key it affects is because they are not supposed to have positional information. A `FailureReason`, together with a path in the config and an optional location (file, line) in the config forms a `ConvertFailure` object, an instance of `ConfigReaderFailure`.

`UnknownKey` is particularly confusing because we decided to add the `key` as a case class field, even though semantically speaking, it should be just a `case object`.

The descriptions are written to play well with the behavior of `ConfigReaderException`. While debugging, if you use `loadConfigOrThrow` and the method throws an exception, the error messages are indexed by key, resulting in a human-friendly message like:

```
  at 'path.to.my.key':
    - Unknown key.
```

If you don't use `loadConfigOrThrow` and inspect errors programatically instead, you should inspect the whole information in `ConvertFailure` instead of just the `FailureReason` objects. That provides you with the full path to the unknown key.

Let me know if this helps you!

**Comment by katameru** [comment]
Yeah, the `key` field confused me, but everything makes sense now. Thanks!
