### ISSUE TITLE
Migrate website documentation to Scala 2.12

### ISSUE THREAD

**Issue by ruippeixotog** [pureconfig/pureconfig#419]
Currently, we enforce that the code snippets in our website run in all Scala versions we support (i.e. Scala 2.11 and Scala 2.12). This means that code will always work for any user, but it also means that sometimes the examples are more complex than they need to, with the most prominent example being the proliferation of `.right` calls needed before Scala 2.12.

Since the majority of our users use Scala 2.12 and, when not multi-versioned, documentation pages typically use the latest versions of the related libraries/languages, it may make sense to make our documentation target Scala 2.12.

What do you think, @jcazevedo and @leifwickland?

**Comment by leifwickland** [comment]
I'm conflicted. Surveys I've seen suggest a lot of scala users are stuck on 2.11 due to Spark. (I am among them.) On the other hand, theoretically Spark support for 2.12 is just around the corner and perhaps the migration floodgates will soon open, so perhaps we could simply show users the nicest possible experience. 

I guess that's to say I'd leave it up to you guys. I don't have a strong feeling.

**Comment by jcazevedo** [comment]
Since I don't think making our documentation multi-versioned is worth the effort, I agree that we should target the latest Scala version.

**Comment by ruippeixotog** [comment]
I don't have a strong feeling either. Since @jcazevedo agrees with the change to Scala 2.12, I did it in #421 👍
