### ISSUE TITLE
pureconfig.Derivation[pureconfig.ConfigReader

### ISSUE THREAD

**Issue by charmby** [pureconfig/pureconfig#455]
run the example
case class Config(dirwatch: DirWatchConfig)
    case class DirWatchConfig(path: Path, filter: String, email: EmailConfig)
    case class EmailConfig(host: String, port: Int, message: String, recipients: Set[Email], sender: Email)

    val config = loadConfigOrThrow[Config]

i get this error:
Error:(34, 35) could not find implicit value for parameter reader:pureconfig.Derivation[pureconfig.ConfigReader

**Comment by ruippeixotog** [comment]
Hi @charmby! Our CI builds [compile the example project](https://github.com/pureconfig/pureconfig/blob/master/.travis.yml#L15) for all supported SBT versions, so it shouldn't be possible for that to happen.

Did you compile the example project as is, or have you copied the code to another project? If it's the latter, can you provide a minimal example project where you're experiencing the issue?

**Comment by charmby** [comment]
hi, @ruippeixotog , Thank you for your reply. As a maven project, i run this example in IDEA. Import this project in my pom like this
```
  <dependency>
            <groupId>com.github.pureconfig</groupId>
            <artifactId>pureconfig_2.12</artifactId>
            <version>0.10.0</version>
        </dependency>

        <dependency>
            <groupId>org.scalamacros</groupId>
            <artifactId>paradise_2.11.0-M7</artifactId>
            <version>2.0.0-M8</version>
        </dependency>

        <dependency>
            <groupId>eu.timepit</groupId>
            <artifactId>refined-pureconfig_2.12</artifactId>
            <version>0.9.4</version>
        </dependency> 
```
coding for that
case class Person(name: String, surname: String)
object Test extends App {
    val conf = ConfigFactory.parseString("{ name: John, surname: Doe }")
    import pureconfig.generic.semiauto._
    implicit val personReader = deriveReader[Person]
    val res: Either[ConfigReaderFailures, Person] = pureconfig.loadConfig[Person](conf)
}

**Comment by dvirf1** [comment]
It happens to me as well. It also happens with 0.10.1 and 0.10.2.
It does not happen with 0.9.2.
I'm cleaning the `target` directory between checks.

**Comment by ruippeixotog** [comment]
Have you imported `import pureconfig.generic.auto._`? Since version 0.10.0 it is now necessary to import `auto` manually for automatic derivation of case classes ([CHANGELOG](https://github.com/pureconfig/pureconfig/blob/master/CHANGELOG.md#0100-oct-30-2018)).

Otherwise, please share with me a self-contained project where the error happens. I cannot reproduce it here and code snippets aren't enough for that :)

**Comment by dvirf1** [comment]
@ruippeixotog due to semantic versioning I expected that the update from 0.9.2 to 0.10.x won't break anything.
The problem is solved now. Thanks.
I think that it is a good idea to add an `implicitNotFound` annotation that suggests this import if the compilation fails, similar to `ExecutionContext`'s message:
> Cannot find an implicit ExecutionContext.
...
If your application does not define an ExecutionContext elsewhere,
consider using Scala's global ExecutionContext by defining
the following:
>
>implicit val ec = ExecutionContext.global

So maybe it should be something like:
>Cannot find an implicit Derivation for ${A}.
If your application does not define a Derivation elsewhere,
consider using PureConfig's auto derivation by defining the following:
>
>import pureconfig.generic.auto._

Would you like me to add it?

**Comment by dvirf1** [comment]
@ruippeixotog 
See PR #456. Feel free to edit the error message if you think it is necessary.

**Comment by ruippeixotog** [comment]
@dvirf1 technically, you should not expect 0.x.y versions to follow any conventions ([semver rules](https://semver.org/#spec-item-4)). In practice, we tend to do minor version increases every time we do introduce major architectural or breaking changes. I agree that it can be misleading sometimes.

@charmby does this solution solve your problem?

**Comment by charmby** [comment]
@ruippeixotog thank you so much.This problem is solved.
