### ISSUE TITLE
Support Java 7 (and use typesafe config 1.2)

### ISSUE THREAD

**Issue by lefou** [pureconfig/pureconfig#5]
Is there a specific reason to not support Java 7?

It seems, that building and testing with Oracle JDK 7 against `com.typesafe.config-1.2.1` (which does not require Java 8) works.

**Comment by melrief** [comment]
The main and only reason why I'm not supporting Java 7 is that the new Typesafe Config releases require Java 8 and using a previous version would be unwise considering that there is no backporting for bug fixes and patches in general. I'm not happy with this side-effect of the Typesafe Config library to be honest but I can't use an outdated configuration library as back-end.

**Comment by lefou** [comment]
That is unfortunate but a legit reason. As this project is not the only one having this issues with typesafe-config, I could imagine there will be either a 1.2-branch or a fork maintaining the Java7 compatibility.

**Comment by lefou** [comment]
Maybe, it's a good idea to explicitly point out the reason for the Java8 requirement in the sbt initializer warning.

**Comment by melrief** [comment]
The idea of creating a branch and maybe publish a special artifact is good, I will add this when I have some time. I will keep this open until it's ready.

For the sbt initializer, you probably are right but I think the README.md should be the first place where this should be written. I noticed that not only I don't say why pureconfig needs Java 8 but I also don't mention it needs Java 8. That's something to fix asap.

**Comment by mekalz** [comment]
It would be good to write the requirement of JDK8 clearly in README.md. And btw, is there any replacement to work with JDK7? I must use JDK7 for some reasons.

**Comment by melrief** [comment]
You are right, I will update the documentation soon. There could be a replacement that works for JDK7 but I've never had the time to work on it. @lefou above wrote that you can use an older version of typesafe config as backend. The issue here is that my initial idea was to abstract from the backend instead of just creating a new branch for Java 7 because a branch would require a lot of work to maintain it and because abstracting from the backend would allow to support other formats, like pure JSON configurations. The backend abstraction is WIP and I don't know of when it will be completed.

**Comment by mslinn** [comment]
Perhaps it is time to close this issue?
