### ISSUE TITLE
Allow passing ClassLoaders to the ConfigSource constructors that can use it

### ISSUE THREAD

**Issue by nigredo-tori** [pureconfig/pureconfig#599]
This was a part of #531, but didn't make it into #541.

`ConfigFactory.parseResources` and its derivatives that don't accept a `ClassLoader` use `Thread.getContextClassLoader` inside, which doesn't mix at all with the threadpool-heavy execution model that the Cats-Effect ecosystem provides, and with the `ClassLoader` wizardry that SBT does by default.

Case in point: https://gitter.im/melrief/pureconfig?at=5d8ddd7573dd29627ebe5ab2.

**Comment by ruippeixotog** [comment]
@nigredo-tori I see that `defaultApplication(ClassLoader)` just calls `defaultApplication(ConfigParseOptions.defaults().setClassLoader(loader))`. Would it work for you if we provided a way to specify custom `ConfigParseOptions`, in order for the API to cover more cases?

**Comment by nigredo-tori** [comment]
@ruippeixotog, sure. But in that case we should mention the context class loader issue in the ScalaDoc for the methods that have that behavior, and point the user towards the `ConfigParseOptions` route - just to make the solution discoverable. At least to me the fact that `ConfigParseOptions` also includes a `ClassLoader` came as a surprise.

**Comment by ruippeixotog** [comment]
#614 closes this. Despite my comment above, after I looked a bit more at `ConfigParseOptions` I decided not to give users that flexibility in default constructors. The name is misleading as many options there have nothing to do with parsing, like the config loader to use, and there are settings that change the semantics intended by `ConfigSource`, like allowing missing files.

Since `classLoader` is only really relevant to methods dealing to resources, I went for the original idea in the issue.
