### ISSUE TITLE
Consider implementing a small zio adapter module

### ISSUE THREAD

**Issue by saraiva132** [pureconfig/pureconfig#639]
There is a zio-config native library but I believe pureconfig has its merits and it might be worthwhile to implement a small ZIO module

**Comment by nigredo-tori** [comment]
As long as ZIO supports cats-effect via interop-cats, we have all the cats-effect syntax available for ZIO monads (at least the ones that have `Sync`). So I think that, unless there is some **ZIO-specific** feature that we want, adding an interop module for ZIO is unwarranted.

However, we might want to add a ZIO example, since setting everything up might not be immediately obvious.
