### ISSUE TITLE
Not obvious naming conventions (no CamelCase support in configs)

### ISSUE THREAD

**Issue by DenisNovac** [pureconfig/pureconfig#690]
Hi everyone.

I made this class for config:
```
case class Config (
  persistent: Boolean,
  appHost: String ,
  appPort: String,
  dbHost: String,
  dbPort: String,
  db: String,
  dbUser: String,
  dbPassword: String) 
```

But this is my config file:

```
persistent = false
app-host = "172.18.1.2"
app-port = "9000"
db-host = "localhost"
db-port = "5432"
db = "postgres"
db-user = "postgres"
db-password = "P@ssw0rd"
```

And i found out this naming conventions through debugger. I think, it'll make sense to write about style conventions in Quick Start section of readme. Or provide support for camel case namings maybe?

**Comment by ruippeixotog** [comment]
Hi @DenisNovac! The [Quick Start](https://pureconfig.github.io/docs/index.html) section shows an example of a config and matching class structure (there's only a link to the config, in fact - we can change that so that it shows the config inline).

The [Case Class](https://pureconfig.github.io/docs/overriding-behavior-for-case-classes.html) section of the documentation explicitly says that configs are expected to be in kebab case and classes should be camel case. It also shows how to change the default field mappings.

**Comment by DenisNovac** [comment]
But there is no camel case example in the quick start which makes it not so quick in some cases.
