### ISSUE TITLE
Clarify type formatting

### ISSUE THREAD

**Issue by Phlosioneer** [pureconfig/pureconfig#7]
Some questions include:
- Does the capitalization of "true" and "false" matter?
- Are values case-sensitive? (e.g. if a "logerrors" value is defined elsewhere and a line refers to it using "logErrors")
- Are commas supported in numbers? (e.g. 1,000,420)
- What characters are valid in a quantity? (e.g. is "10 blocks of C4" a valid quantity? or "30 m/s^2"?)
- Is there support for quantities with prefixes? (e.g. cost = $10, color = 0xFFA512)
- What is the behavior of a quantity with whitespace? (e.g. ammo = 25 shotgun shells)
- When using a schema file, are quantity names case sensitive? (e.g. schema has "size: quantity(meters)" and config file has "size = 12 Meters")
- Is there a limitation on name size? what about value size? (e.g. a value is a huge URL, a paragraph of text to be used in dialog, a number that's too large to fit in an integer, etc. or key is for example a Twitch Stream Id or a product serial number)
- What's the rounding behavior for numbers with too many decimal places for a double to hold?
- More details on the typing of strings; using the string("mm-dd-yyyy") example, how does a parser know that mm, dd, and yyyy are user provided, but '-' is part of the formatting?
- When writing types, are type names case sensitive?

It'd be a nice feature to allow restrictions to be placed on values in a schema file; for example, instead of just a string, it's a string with at most 140 characters, or a number between 1 and 12, etc.
It'd also be a nice feature to allow multiple possible types - for example, birthdate is either "MM-DD-YYYY" or "MM-DD". Or ammo is either quantity("shotgun shells") or quantity("bullets").

**Comment by Phlosioneer** [comment]
Another question I just encountered: if a number ends in a period but nothing else afterwards, does it count as an integer, a double, or a string?

**Comment by pureconfig** [comment]
Great input!

Last question first: I'd say that infers to a double. If a string was meant, you can always quote.

> Does the capitalization of "true" and "false" matter?

No

> Are values case-sensitive? (e.g. if a "logerrors" value is defined elsewhere and a line refers to it using "logErrors")

I don't think a format has *any* say with regards to values. It must be up to the application to make decisions here. I can, however, imagine the schema being able to specify the rules here. But of course, it's not a good idea to over engineers this.

> Is there a limitation on name size? 

No, but the implementation must of course deal with any buffer/memory size related issues.

> Are commas supported in numbers? (e.g. 1,000,420)

It would be nice to allow thousand separators, but that would make it rather hard to have an array of integers. Allowing it in non-array contexts only seems inconsistent. Maybe 1´1000´420 ? 

> What's the rounding behavior for numbers with too many decimal places for a double to hold?

For a configuration format, saturation rounding makes sense to me (cap at the maximum)

> What characters are valid in a quantity? (e.g. is "10 blocks of C4" a valid quantity? or "30 m/s^2"?)
> What is the behavior of a quantity with whitespace?

I don't see a problem accepting anything, as long as the property starts with a digit. Have to think more carefully about it though.

> When writing types, are type names case sensitive?

I'd say yes, but more thought is needed. We can start with case sensitive, then relax if it turns out to be OK to do so.

**Comment by Phlosioneer** [comment]
> I don't think a format has any say with regards to values. It must be up to the application to make decisions here. I can, however, imagine the schema being able to specify the rules here. But of course, it's not a good idea to over engineers this.

Ah, I was unclear. When I said values, I suppose I meant keys. What I mean is something like this:
```
logerrors = true

# etc...

logwarnings => logErrors
```

Awesome though, I'll keep this open until I get around to writing tests for these.
