### ISSUE TITLE
"0" is not a valid FiniteDuration anymore

### ISSUE THREAD

**Issue by ruippeixotog** [pureconfig/pureconfig#71]
On pureconfig 0.3.x, "0" was accepted as a valid duration. It's the only case where the time unit does not matter, and Akka frequently uses that value in their configs. However, in pureconfig 0.4.0 "0" throws a parsing error.

Can you add again that special case? As a motivating use case, I frequently use values from akka-actor in my refefence.conf as defaults for my own domain configs.

**Comment by melrief** [comment]
Thanks for the report, @jcazevedo fixed it few minutes ago and it's already merged to master. I would like to see also #69 to be merged in master before we release the next version of pureconfig but only if you don't need it right now. If you need it now we'll publish it today, otherwise in a couple of days max.

**Comment by ruippeixotog** [comment]
No problem, I can keep using 0.3.3 for a few days until you release the new version :) Thank you!
