### ISSUE TITLE
`ConfigFieldMapping` and `ProductHint` concepts

### ISSUE THREAD

**Issue by ruippeixotog** [pureconfig/pureconfig#76]
The current naming conventions currently only apply (and are only relevant) to products. In my view, a `ConfigFieldMapping` is a just a special case of a `ProductHint` - a way for developers to "advise" pureconfig on how to derive converters for certain kinds of products.

In the derivation code a `ConfigFieldMapping` is already handled just like a `CoproductHint` and a first version of `ProductHint` could start to have an interface just equal to the current `ConfigFieldMapping`. However, the more general concept would allow us to add in the future new ways to customize how products are converted. One example that comes to my mind is customizing how `Option` fields should be handled (currently they are a special case).

By separating the concept of `ConfigFieldMapping` from a `ProductHint`, we could start to use `ConfigFieldMapping` for both products and coproducts. The current `FieldCoproductHint` could take an instance of `ConfigFieldMapping` instead of having a `fieldValue` function, for example (that is actually something that we can start doing now, but the semantics would be a bit muddier IMO).

What do you think of this change?

**Comment by ruippeixotog** [comment]
Another thing that would be useful in a `ProductHint`: how should unknown keys be treated? If we see in a config a key that has no matching field in the product, do we want to be strict and throw an error or do we want to ignore it? Like naming conventions, we probably want a default behavior most of the time and have the ability to customize case-by-case.

**Comment by melrief** [comment]
I like this idea and I think we should consider it. In particular, I think the separation of `ConfigFieldMapping` from a `ProductHint` is good design.
I'm not sure how to handle unknown keys. I would like to let the user configure it but I'm not sure what should be default. I would go with the most conservative strategy, which is the strict strategy that you were talking about.
I personally like the idea that config keys with no matching fields are ignored because this allows to reduce or change the fields of the configuration class and still be able to use a configuration available. For instance, two versions of a program could use two different configuration schema but one single configuration could be provided with the fields of both schemas. I used this in the past and it worked. The issue with this is that it's easier to make mistakes in the configuration which means that probably we don't want it as default behavior. A more strict and safe approach is better imho.

**Comment by jcazevedo** [comment]
I'm also supportive of the idea of a `ProductHint`. One other thing that we can configure through a `ProductHint`, besides the ones mentioned before, is whether or not we should apply default arguments of case classes when a field is missing from a config.

**Comment by ruippeixotog** [comment]
Regarding the default for unknown keys, I also prefer the strict one as it ensures `reference.conf` files are updated, a thing without which I already shot myself in the foot many times :) However, I definitely want the option to turn that off. One "pattern" I like is having in `reference.conf` default values for several or all options of a coproduct - that way, in `application.conf` users can get a working config by defining only the `type` of the config. Hence the need for a `ProductHint` with that.

Making default arguments optional is also a good option to have. In fact, if it was up to me I would have that feature disabled by default. I rely heavily on `reference.conf` files, as many Lightbend libraries do. They are used as a dictionary of default values, which one can look to if he/she wants to override some setting. Having them on code is a bit confusing and harder to maintain. I don't know how everyone else uses `reference.conf` files (if they use them at all), but other people might have different use pattens.

Anyway, I'll get to work on a pull request for `ProductHints` this weekend and then we can further discuss there :)

**Comment by melrief** [comment]
@ruippeixotog we merged #90 and #95, do you think we should close this or keep opening for the missing parts?

**Comment by ruippeixotog** [comment]
I think we can close this. The general concept of a hint for products is there; new features could be naturally added later :)
