### ISSUE TITLE
java.lang.NoClassDefFoundError: pureconfig/generic/MapShapedReader$WithDefaults

### ISSUE THREAD

**Issue by t3hnar** [pureconfig/pureconfig#800]
Hello

Looks like version `0.13.0` is not backward compatible with `0.12.3`

Basically I have library compiled with `0.12.3`, however after upgrading application to `0.13.0` which is using my library I get in runtime: 

```
java.lang.NoClassDefFoundError: pureconfig/generic/MapShapedReader$WithDefaults
```

**Comment by leifwickland** [comment]
@mberndt123,

Thanks for using Pureconfig. 

What you observed is expected behavior. Pureconfig follows the [typical scala library practice](https://docs.scala-lang.org/overviews/core/binary-compatibility-for-library-authors.html#recommended-versioning-scheme) that releases with a major version of `0` are *not* binary compatible between minor version bumps.

**Comment by t3hnar** [comment]
Thanks for explaining, did not know about exceptional case of '0.x.x' versions. Then I have a really huge problem bumping the dependencies :(


Anyway thanks for such a nice library.
