### ISSUE TITLE
Add number of bytes class and ConfigConvert

### ISSUE THREAD

**Issue by melrief** [pureconfig/pureconfig#86]
Typesafe config supports [`getBytes`](http://typesafehub.github.io/config/latest/api/com/typesafe/config/Config.html#getBytes-java.lang.String-) to read the number of bytes from a human friendly string such as `10MB`. The spec for this format is [here](https://github.com/typesafehub/config/blob/master/HOCON.md#size-in-bytes-format). It would be nice to add this to pureconfig. The way I think we should do this is slightly different from what typesafe config does: I would add a class Bytes and create a `ConfigConvert` for it. The obvious issue with this is that it would be different from what you have in Typesafe config.

**Comment by leifwickland** [comment]
@melrief I really like this the idea. My initial take is that the `Bytes` class might be similar in design to the scala`Duration` class, tracking a scalar and a unit.

I think my inclination might be to call that class `ByteSize` rather than`Bytes` in order to avoid conflicts who have a byte array wrapper called `Bytes`.

**Comment by melrief** [comment]
@leifwickland you are right and I can think of one library that uses the name `Bytes` for binary format encoding and decoding. `ByteSize` is better.

**Comment by derekmorr** [comment]
Is this still needed now that the squants module was merged? Squants has an `Information` type that supports bytes and both the decimal (MB, GB, ...) and binary (MiB, GiB, ...) suffixes.

OTOH, it might be nice to have a converter that doesn't depend on squants.

**Comment by jcazevedo** [comment]
I prefer not introducing a custom type in PureConfig's core. I think we can support reading strings the method `getBytes` allows into numeric types (`Float`, `Double`, `Short`, `Int` and `Long`), but otherwise rely on external libraries for more semantically rich types (such as Squants, as @derekmorr suggested).

**Comment by melrief** [comment]
@derekmorr @jcazevedo you have good points and I think I prefer to not having it in core too after reading them. I should think less about typesafe config and more about what we'd like pureconfig core to be. Closing this.

@stsatlantis this was assigned to you but I haven't received any update here or on gitter. I hope it's fine for you too if we close this, sorry for the confusion.

**Comment by stsatlantis** [comment]
Np I forgot to send the PR but np I've learned a lot from it :)
