### ISSUE TITLE
Abstract over effect in ConfigConverter

### ISSUE THREAD

**Issue by 13h3r** [pureconfig/pureconfig#91]
Right now `Try` is built in into `ConfigConverter` it will be good to make it pluggable. Most usable candidates are `Validated`, `Either`, `Id`.

**Comment by melrief** [comment]
I would prefer to stick with one type instead of making the type pluggable because I've always found typeclasses for output types difficult to read. `Try` was picked because of typesafe config and in general the fact that we work with an exception-based Java API. With time I think it's becoming more and more clear that `Try` itself is not the best type for output and more suitable types, like `Validated` or `Either`, could be used to, for instance, collect errors.

I propose to discuss about this and decide the direction of our public API before we do the changes. `Try` is showing its limits and `Either[NonEmptyList[PureconfigError], A]` is starting to look as a better type to me.

FYI it is entirely possible to keep using `Try` but collect the errors via special `Exception`. I actually have a patch on my local computer doing this and I was going to propose it before @13h3r wrote this. For instance, the code for `hConsConfigConvert` could be changed like this

```scala
    override def fromConfigObject(co: ConfigObject, default: Option[V] :: U): Try[FieldType[K, V] :: T] = {
      val keyStr = mapping(key.value.toString().tail)
      val valueOrError =
        improveFailure[V](
          (co.get(keyStr), vFieldConvert.value) match {
            case (null, converter: AllowMissingKey) =>
              converter.from(co.get(keyStr))
            case (null, _) =>
              default.head.fold[Try[V]](Failure(CannotConvertNullException))(Success(_))
            case (value, converter) =>
              converter.from(value)
          },
          keyStr, co.get(keyStr))
      val tailOrError =
        tConfigConvert.value.fromWithDefault(co, default.tail)
      (valueOrError, tailOrError) match {
        case (Success(value), Success(tail)) => Success(field[K](value) :: tail)
        case (Failure(error1), Failure(error2)) => Failure(MultipleExceptions.of(error1, error2))
        case (Failure(error), _) => Failure(error)
        case (_, Failure(error)) => Failure(error)
      }
    }
```

Where `MultipleExceptions` is an `Exception` that contains many exceptions. It's not very elegant but it would work and the developer should be able to extract all the errors from `MultipleExceptions` very easily.

**Comment by Daenyth** [comment]
As a dev I'd much prefer working with `Either[NEL, A]` or `Validation[NEL, A]`

**Comment by melrief** [comment]
@Daenyth @13h3r with `0.6.0` we switched to `Either[ConfigReaderFailure, A]` where `ConfigReaderFailur` is a custom `NEL` that can easily be mapped to the counterpart in cats or scalaz. I'll close this.
