### ISSUE TITLE
Clarifying nested object conversion

### ISSUE THREAD

**Issue by eadgbear** [pureconfig/pureconfig#98]
I'm trying to understand how I can achieve the following:

```scala
sealed trait TC
case class ITC(count:Int, work:TC) extends TC
case class SSTC(query:String, args:List[AnyRef]) extends TC

case class Global(work:List[TC], runtime:Option[FiniteDuration)
```

I can't seem to understand the process that would be required to achieve something like this. I get the exception listed in the documentation (i.e ```could not find implicit value for parameter conv: pureconfig.ConfigConvert[Global]```) but I can't for the life of me figure out what's causing it or what steps I can use to fix it.

I've tried to create a custom converter, but I'm not sure how to leverage pureconfig to load the types it already knows about.

**Comment by melrief** [comment]
The error means that pureconfig cannot find the `ConfigConvert` instance for one or more types in `Global` and consequently it cannot derive the `ConfigConvert` for `Global` itself. Now the question is which type. There is a way to check the type by using a scala console. Basically you can check every type until you get an error

```scala
> import pureconfig.ConfigConvert
> ConfigConvert[Int]
res0: pureconfig.ConfigConvert[Int] = pureconfig.ConfigConvert$$anon$5@4737d730
> // Int has a ConfigConvert, no error
> ConfigConvert[String]
res1: pureconfig.ConfigConvert[String] = pureconfig.ConfigConvert$$anon$5@1683a9f5
> // same for String
> ConfigConvert[FiniteDuration]
res2: pureconfig.ConfigConvert[FiniteDuration] = pureconfig.ConfigConvert$$anon$6@489b26b1
> // same for FiniteDuration...
> ConfigConvert[AnyVal]
<console>:17: error: could not find implicit value for parameter conv: pureconfig.ConfigConvert[AnyVal]
       ConfigConvert[AnyVal]
> // ...but not for AnyVal! The issue is AnyVal
```

The issue is that `AnyVal` doesn't have a `ConfigConvert` because it's an [`abstract class`](http://www.scala-lang.org/api/2.12.x/scala/AnyVal.html) and not a sealed family. The good news is that `AnyVal` contains all types that can easily be converted from/to String and it should be easy to implement a  `ConfigConverter` for it.
Scala defines nine types that are subclasses of `AnyVal`, which are `Double`, `Float`, `Long`, `Int`, `Char`, `Short`, `Byte`, `Unit` and `Boolean`. pureconfig has `ConfigConvert` instances for `Double`, `Float`, `Long`, `Int`, `Short` and `Boolean`. You can either decide to ignore the remaining types, which are `Char`, `Byte` and `Unit`, or create `ConfigConvert` for them. It's up to you but here I'm going to ignore them and show how to create the `ConfigConvert` of `AnyVal` from existing `ConfigConvert` instances for the subclasses. The code that I'm going to use can be enhanced with the missing `ConfigConvert` instances. The code for `AnyVal` would be:

```scala
import com.typesafe.config.{ConfigFactory,ConfigValue}
import pureconfig._
import pureconfig.ConfigConvert._
import scala.util.Try

implicit val anyValConfigConvert: ConfigConvert[AnyVal] = new ConfigConvert[AnyVal] {

  def from(cv: ConfigValue): Try[AnyVal] =
      ConfigConvert[Double].from(cv) orElse
      ConfigConvert[Int].from(cv)    orElse
      ConfigConvert[Long].from(cv)   orElse
      ConfigConvert[Float].from(cv)  orElse
      ConfigConvert[Short].from(cv)  orElse
      ConfigConvert[Boolean].from(cv)

  def to(a: AnyVal): ConfigValue = ???
}
```

Now that there is an instance of `ConfigConvert` for `AnyVal`, pureconfig can derive `Global`:

```scala
> val config = ConfigFactory.parseString(
      """{
        | work: [
        |   { type: "sstc",
        |     query: "na",
        |     args: [ 1, 2.4, "3", false ]
        |    }
        | ],
        | runtime: 1s
        |}""".stripMargin)
> println(loadConfig[Global](config))
Success(Global(List(SSTC(na,List(1.0, 2.4, 3.0, false))),Some(1 second)))
```

**Comment by eadgbear** [comment]
Thanks!

Once I put this in as a package object it worked wonderfully.

**Comment by eadgbear** [comment]
Although I seem to be running into an inconsistency. When running it through ```sbt console``` I can validate that every class has a ConfigConvert. When I try to run tests through my IDE (Intellij) it results in the same error as above.

**Comment by melrief** [comment]
I'm actually not sure why, it works for me in intellij. I wonder what the issue is. Do you have a minimal self-contained example that I can try to inspect?

**Comment by eadgbear** [comment]
I don't on-hand as I've refactored to make it work.

What seemed to trigger it was having an object type with non-apply
functionality. Once I got rid of the static object for the sealed trait it
works.

**Comment by melrief** [comment]
Sounds a lot like a bug. I'll have a look when I have time, it shouldn't be too difficult to recreate if that's the issue. Thanks for the report.

**Comment by eadgbear** [comment]
I've made a bit of a discovery in this regard. If I put all of the definitions in the same file, the problem goes away.

**Comment by melrief** [comment]
I'm closing this for now because the issue is a limitation of Scala and not of PureConfig. Moreover, a workaround has been found.

**Comment by sidhant92** [comment]
@melrief What workaround has been found for this? Im having the same issue. My Nested Case Classes is not compiling. Its not related to AnyVal.
